// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/common_msgs/localization_msgs/localization_status.proto

#ifndef PROTOBUF_modules_2fcommon_5fmsgs_2flocalization_5fmsgs_2flocalization_5fstatus_2eproto__INCLUDED
#define PROTOBUF_modules_2fcommon_5fmsgs_2flocalization_5fmsgs_2flocalization_5fstatus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace apollo {
namespace localization {
class MsfGnssMapOffset;
class MsfGnssMapOffsetDefaultTypeInternal;
extern MsfGnssMapOffsetDefaultTypeInternal _MsfGnssMapOffset_default_instance_;
class MsfInitDetails;
class MsfInitDetailsDefaultTypeInternal;
extern MsfInitDetailsDefaultTypeInternal _MsfInitDetails_default_instance_;
class MsfSensorMsgStatus;
class MsfSensorMsgStatusDefaultTypeInternal;
extern MsfSensorMsgStatusDefaultTypeInternal _MsfSensorMsgStatus_default_instance_;
class MsfStatus;
class MsfStatusDefaultTypeInternal;
extern MsfStatusDefaultTypeInternal _MsfStatus_default_instance_;
}  // namespace localization
}  // namespace apollo

namespace apollo {
namespace localization {

namespace protobuf_modules_2fcommon_5fmsgs_2flocalization_5fmsgs_2flocalization_5fstatus_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_modules_2fcommon_5fmsgs_2flocalization_5fmsgs_2flocalization_5fstatus_2eproto

enum LocalLidarStatus {
  MSF_LOCAL_LIDAR_NORMAL = 0,
  MSF_LOCAL_LIDAR_MAP_MISSING = 1,
  MSF_LOCAL_LIDAR_EXTRINSICS_MISSING = 2,
  MSF_LOCAL_LIDAR_MAP_LOADING_FAILED = 3,
  MSF_LOCAL_LIDAR_NO_OUTPUT = 4,
  MSF_LOCAL_LIDAR_OUT_OF_MAP = 5,
  MSF_LOCAL_LIDAR_NOT_GOOD = 6,
  MSF_LOCAL_LIDAR_UNDEFINED_STATUS = 7
};
bool LocalLidarStatus_IsValid(int value);
const LocalLidarStatus LocalLidarStatus_MIN = MSF_LOCAL_LIDAR_NORMAL;
const LocalLidarStatus LocalLidarStatus_MAX = MSF_LOCAL_LIDAR_UNDEFINED_STATUS;
const int LocalLidarStatus_ARRAYSIZE = LocalLidarStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* LocalLidarStatus_descriptor();
inline const ::std::string& LocalLidarStatus_Name(LocalLidarStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    LocalLidarStatus_descriptor(), value);
}
inline bool LocalLidarStatus_Parse(
    const ::std::string& name, LocalLidarStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LocalLidarStatus>(
    LocalLidarStatus_descriptor(), name, value);
}
enum LocalLidarQuality {
  MSF_LOCAL_LIDAR_VERY_GOOD = 0,
  MSF_LOCAL_LIDAR_GOOD = 1,
  MSF_LOCAL_LIDAR_NOT_BAD = 2,
  MSF_LOCAL_LIDAR_BAD = 3
};
bool LocalLidarQuality_IsValid(int value);
const LocalLidarQuality LocalLidarQuality_MIN = MSF_LOCAL_LIDAR_VERY_GOOD;
const LocalLidarQuality LocalLidarQuality_MAX = MSF_LOCAL_LIDAR_BAD;
const int LocalLidarQuality_ARRAYSIZE = LocalLidarQuality_MAX + 1;

const ::google::protobuf::EnumDescriptor* LocalLidarQuality_descriptor();
inline const ::std::string& LocalLidarQuality_Name(LocalLidarQuality value) {
  return ::google::protobuf::internal::NameOfEnum(
    LocalLidarQuality_descriptor(), value);
}
inline bool LocalLidarQuality_Parse(
    const ::std::string& name, LocalLidarQuality* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LocalLidarQuality>(
    LocalLidarQuality_descriptor(), name, value);
}
enum LocalLidarConsistency {
  MSF_LOCAL_LIDAR_CONSISTENCY_00 = 0,
  MSF_LOCAL_LIDAR_CONSISTENCY_01 = 1,
  MSF_LOCAL_LIDAR_CONSISTENCY_02 = 2,
  MSF_LOCAL_LIDAR_CONSISTENCY_03 = 3
};
bool LocalLidarConsistency_IsValid(int value);
const LocalLidarConsistency LocalLidarConsistency_MIN = MSF_LOCAL_LIDAR_CONSISTENCY_00;
const LocalLidarConsistency LocalLidarConsistency_MAX = MSF_LOCAL_LIDAR_CONSISTENCY_03;
const int LocalLidarConsistency_ARRAYSIZE = LocalLidarConsistency_MAX + 1;

const ::google::protobuf::EnumDescriptor* LocalLidarConsistency_descriptor();
inline const ::std::string& LocalLidarConsistency_Name(LocalLidarConsistency value) {
  return ::google::protobuf::internal::NameOfEnum(
    LocalLidarConsistency_descriptor(), value);
}
inline bool LocalLidarConsistency_Parse(
    const ::std::string& name, LocalLidarConsistency* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LocalLidarConsistency>(
    LocalLidarConsistency_descriptor(), name, value);
}
enum GnssConsistency {
  MSF_GNSS_CONSISTENCY_00 = 0,
  MSF_GNSS_CONSISTENCY_01 = 1,
  MSF_GNSS_CONSISTENCY_02 = 2,
  MSF_GNSS_CONSISTENCY_03 = 3
};
bool GnssConsistency_IsValid(int value);
const GnssConsistency GnssConsistency_MIN = MSF_GNSS_CONSISTENCY_00;
const GnssConsistency GnssConsistency_MAX = MSF_GNSS_CONSISTENCY_03;
const int GnssConsistency_ARRAYSIZE = GnssConsistency_MAX + 1;

const ::google::protobuf::EnumDescriptor* GnssConsistency_descriptor();
inline const ::std::string& GnssConsistency_Name(GnssConsistency value) {
  return ::google::protobuf::internal::NameOfEnum(
    GnssConsistency_descriptor(), value);
}
inline bool GnssConsistency_Parse(
    const ::std::string& name, GnssConsistency* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GnssConsistency>(
    GnssConsistency_descriptor(), name, value);
}
enum GnssPositionType {
  NONE = 0,
  FIXEDPOS = 1,
  FIXEDHEIGHT = 2,
  FLOATCONV = 4,
  WIDELANE = 5,
  NARROWLANE = 6,
  DOPPLER_VELOCITY = 8,
  SINGLE = 16,
  PSRDIFF = 17,
  WAAS = 18,
  PROPOGATED = 19,
  OMNISTAR = 20,
  L1_FLOAT = 32,
  IONOFREE_FLOAT = 33,
  NARROW_FLOAT = 34,
  L1_INT = 48,
  WIDE_INT = 49,
  NARROW_INT = 50,
  RTK_DIRECT_INS = 51,
  INS_SBAS = 52,
  INS_PSRSP = 53,
  INS_PSRDIFF = 54,
  INS_RTKFLOAT = 55,
  INS_RTKFIXED = 56,
  INS_OMNISTAR = 57,
  INS_OMNISTAR_HP = 58,
  INS_OMNISTAR_XP = 59,
  OMNISTAR_HP = 64,
  OMNISTAR_XP = 65,
  PPP_CONVERGING = 68,
  PPP = 69,
  INS_PPP_Converging = 73,
  INS_PPP = 74,
  MSG_LOSS = 91
};
bool GnssPositionType_IsValid(int value);
const GnssPositionType GnssPositionType_MIN = NONE;
const GnssPositionType GnssPositionType_MAX = MSG_LOSS;
const int GnssPositionType_ARRAYSIZE = GnssPositionType_MAX + 1;

const ::google::protobuf::EnumDescriptor* GnssPositionType_descriptor();
inline const ::std::string& GnssPositionType_Name(GnssPositionType value) {
  return ::google::protobuf::internal::NameOfEnum(
    GnssPositionType_descriptor(), value);
}
inline bool GnssPositionType_Parse(
    const ::std::string& name, GnssPositionType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GnssPositionType>(
    GnssPositionType_descriptor(), name, value);
}
enum ImuMsgDelayStatus {
  IMU_DELAY_NORMAL = 0,
  IMU_DELAY_1 = 1,
  IMU_DELAY_2 = 2,
  IMU_DELAY_3 = 3,
  IMU_DELAY_ABNORMAL = 4
};
bool ImuMsgDelayStatus_IsValid(int value);
const ImuMsgDelayStatus ImuMsgDelayStatus_MIN = IMU_DELAY_NORMAL;
const ImuMsgDelayStatus ImuMsgDelayStatus_MAX = IMU_DELAY_ABNORMAL;
const int ImuMsgDelayStatus_ARRAYSIZE = ImuMsgDelayStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* ImuMsgDelayStatus_descriptor();
inline const ::std::string& ImuMsgDelayStatus_Name(ImuMsgDelayStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    ImuMsgDelayStatus_descriptor(), value);
}
inline bool ImuMsgDelayStatus_Parse(
    const ::std::string& name, ImuMsgDelayStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ImuMsgDelayStatus>(
    ImuMsgDelayStatus_descriptor(), name, value);
}
enum ImuMsgMissingStatus {
  IMU_MISSING_NORMAL = 0,
  IMU_MISSING_1 = 1,
  IMU_MISSING_2 = 2,
  IMU_MISSING_3 = 3,
  IMU_MISSING_4 = 4,
  IMU_MISSING_5 = 5,
  IMU_MISSING_ABNORMAL = 6
};
bool ImuMsgMissingStatus_IsValid(int value);
const ImuMsgMissingStatus ImuMsgMissingStatus_MIN = IMU_MISSING_NORMAL;
const ImuMsgMissingStatus ImuMsgMissingStatus_MAX = IMU_MISSING_ABNORMAL;
const int ImuMsgMissingStatus_ARRAYSIZE = ImuMsgMissingStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* ImuMsgMissingStatus_descriptor();
inline const ::std::string& ImuMsgMissingStatus_Name(ImuMsgMissingStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    ImuMsgMissingStatus_descriptor(), value);
}
inline bool ImuMsgMissingStatus_Parse(
    const ::std::string& name, ImuMsgMissingStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ImuMsgMissingStatus>(
    ImuMsgMissingStatus_descriptor(), name, value);
}
enum ImuMsgDataStatus {
  IMU_DATA_NORMAL = 0,
  IMU_DATA_ABNORMAL = 1,
  IMU_DATA_OTHER = 2
};
bool ImuMsgDataStatus_IsValid(int value);
const ImuMsgDataStatus ImuMsgDataStatus_MIN = IMU_DATA_NORMAL;
const ImuMsgDataStatus ImuMsgDataStatus_MAX = IMU_DATA_OTHER;
const int ImuMsgDataStatus_ARRAYSIZE = ImuMsgDataStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* ImuMsgDataStatus_descriptor();
inline const ::std::string& ImuMsgDataStatus_Name(ImuMsgDataStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    ImuMsgDataStatus_descriptor(), value);
}
inline bool ImuMsgDataStatus_Parse(
    const ::std::string& name, ImuMsgDataStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ImuMsgDataStatus>(
    ImuMsgDataStatus_descriptor(), name, value);
}
enum MsfRunningStatus {
  MSF_SOL_LIDAR_GNSS = 0,
  MSF_SOL_X_GNSS = 1,
  MSF_SOL_LIDAR_X = 2,
  MSF_SOL_LIDAR_XX = 3,
  MSF_SOL_LIDAR_XXX = 4,
  MSF_SOL_X_X = 5,
  MSF_SOL_X_XX = 6,
  MSF_SOL_X_XXX = 7,
  MSF_SSOL_LIDAR_GNSS = 8,
  MSF_SSOL_X_GNSS = 9,
  MSF_SSOL_LIDAR_X = 10,
  MSF_SSOL_LIDAR_XX = 11,
  MSF_SSOL_LIDAR_XXX = 12,
  MSF_SSOL_X_X = 13,
  MSF_SSOL_X_XX = 14,
  MSF_SSOL_X_XXX = 15,
  MSF_NOSOL_LIDAR_GNSS = 16,
  MSF_NOSOL_X_GNSS = 17,
  MSF_NOSOL_LIDAR_X = 18,
  MSF_NOSOL_LIDAR_XX = 19,
  MSF_NOSOL_LIDAR_XXX = 20,
  MSF_NOSOL_X_X = 21,
  MSF_NOSOL_X_XX = 22,
  MSF_NOSOL_X_XXX = 23,
  MSF_RUNNING_INIT = 24,
  MSF_REINIT_ABNORMALLY = 25
};
bool MsfRunningStatus_IsValid(int value);
const MsfRunningStatus MsfRunningStatus_MIN = MSF_SOL_LIDAR_GNSS;
const MsfRunningStatus MsfRunningStatus_MAX = MSF_REINIT_ABNORMALLY;
const int MsfRunningStatus_ARRAYSIZE = MsfRunningStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsfRunningStatus_descriptor();
inline const ::std::string& MsfRunningStatus_Name(MsfRunningStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsfRunningStatus_descriptor(), value);
}
inline bool MsfRunningStatus_Parse(
    const ::std::string& name, MsfRunningStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsfRunningStatus>(
    MsfRunningStatus_descriptor(), name, value);
}
enum MsfInitPoseSource {
  UNKNOWN_SOURCE = 0,
  GNSS_HEADING = 1,
  LOCAL_SEARCH_FROM_INTEGPVA = 2,
  LOCAL_SEARCH_FROM_FILE = 3,
  LOCAL_UPDATE_FROM_FILE = 4,
  USER_INTERACTION = 5,
  INSPVA_RECORD = 6,
  GNSS_VELOCITY = 7,
  GLOBAL_LIDAR = 8
};
bool MsfInitPoseSource_IsValid(int value);
const MsfInitPoseSource MsfInitPoseSource_MIN = UNKNOWN_SOURCE;
const MsfInitPoseSource MsfInitPoseSource_MAX = GLOBAL_LIDAR;
const int MsfInitPoseSource_ARRAYSIZE = MsfInitPoseSource_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsfInitPoseSource_descriptor();
inline const ::std::string& MsfInitPoseSource_Name(MsfInitPoseSource value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsfInitPoseSource_descriptor(), value);
}
inline bool MsfInitPoseSource_Parse(
    const ::std::string& name, MsfInitPoseSource* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsfInitPoseSource>(
    MsfInitPoseSource_descriptor(), name, value);
}
enum MsfGnssMapOffsetStatus {
  MSF_LOCAL_GNSS_MAP_OFFSET_NORMAL = 0,
  MSF_LOCAL_GNSS_MAP_OFFSET_ABNORMAL = 1
};
bool MsfGnssMapOffsetStatus_IsValid(int value);
const MsfGnssMapOffsetStatus MsfGnssMapOffsetStatus_MIN = MSF_LOCAL_GNSS_MAP_OFFSET_NORMAL;
const MsfGnssMapOffsetStatus MsfGnssMapOffsetStatus_MAX = MSF_LOCAL_GNSS_MAP_OFFSET_ABNORMAL;
const int MsfGnssMapOffsetStatus_ARRAYSIZE = MsfGnssMapOffsetStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsfGnssMapOffsetStatus_descriptor();
inline const ::std::string& MsfGnssMapOffsetStatus_Name(MsfGnssMapOffsetStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsfGnssMapOffsetStatus_descriptor(), value);
}
inline bool MsfGnssMapOffsetStatus_Parse(
    const ::std::string& name, MsfGnssMapOffsetStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsfGnssMapOffsetStatus>(
    MsfGnssMapOffsetStatus_descriptor(), name, value);
}
enum MsfInitPoseStatus {
  INIT_WAITING = 0,
  INIT_DOING = 1,
  INIT_SUCCESSFUL = 2,
  INIT_FAILED = 3,
  INIT_TERMINATED = 4
};
bool MsfInitPoseStatus_IsValid(int value);
const MsfInitPoseStatus MsfInitPoseStatus_MIN = INIT_WAITING;
const MsfInitPoseStatus MsfInitPoseStatus_MAX = INIT_TERMINATED;
const int MsfInitPoseStatus_ARRAYSIZE = MsfInitPoseStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsfInitPoseStatus_descriptor();
inline const ::std::string& MsfInitPoseStatus_Name(MsfInitPoseStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsfInitPoseStatus_descriptor(), value);
}
inline bool MsfInitPoseStatus_Parse(
    const ::std::string& name, MsfInitPoseStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsfInitPoseStatus>(
    MsfInitPoseStatus_descriptor(), name, value);
}
enum MSFInitStatus {
  MSF_INIT = 0,
  MSF_ALIGNING = 1,
  MSF_ALIGNED_INIT = 2,
  MSF_ALIGNED_CONVERGED = 3,
  MSF_ALIGNED_CONVERGING = 4,
  MSF_ALIGNED_GOOD = 5,
  MSF_ALIGNED_VALID = 6
};
bool MSFInitStatus_IsValid(int value);
const MSFInitStatus MSFInitStatus_MIN = MSF_INIT;
const MSFInitStatus MSFInitStatus_MAX = MSF_ALIGNED_VALID;
const int MSFInitStatus_ARRAYSIZE = MSFInitStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* MSFInitStatus_descriptor();
inline const ::std::string& MSFInitStatus_Name(MSFInitStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    MSFInitStatus_descriptor(), value);
}
inline bool MSFInitStatus_Parse(
    const ::std::string& name, MSFInitStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MSFInitStatus>(
    MSFInitStatus_descriptor(), name, value);
}
// ===================================================================

class MsfSensorMsgStatus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.localization.MsfSensorMsgStatus) */ {
 public:
  MsfSensorMsgStatus();
  virtual ~MsfSensorMsgStatus();

  MsfSensorMsgStatus(const MsfSensorMsgStatus& from);

  inline MsfSensorMsgStatus& operator=(const MsfSensorMsgStatus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MsfSensorMsgStatus(MsfSensorMsgStatus&& from) noexcept
    : MsfSensorMsgStatus() {
    *this = ::std::move(from);
  }

  inline MsfSensorMsgStatus& operator=(MsfSensorMsgStatus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsfSensorMsgStatus& default_instance();

  static inline const MsfSensorMsgStatus* internal_default_instance() {
    return reinterpret_cast<const MsfSensorMsgStatus*>(
               &_MsfSensorMsgStatus_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MsfSensorMsgStatus* other);
  friend void swap(MsfSensorMsgStatus& a, MsfSensorMsgStatus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MsfSensorMsgStatus* New() const PROTOBUF_FINAL { return New(NULL); }

  MsfSensorMsgStatus* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MsfSensorMsgStatus& from);
  void MergeFrom(const MsfSensorMsgStatus& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MsfSensorMsgStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.localization.ImuMsgDelayStatus imu_delay_status = 1;
  bool has_imu_delay_status() const;
  void clear_imu_delay_status();
  static const int kImuDelayStatusFieldNumber = 1;
  ::apollo::localization::ImuMsgDelayStatus imu_delay_status() const;
  void set_imu_delay_status(::apollo::localization::ImuMsgDelayStatus value);

  // optional .apollo.localization.ImuMsgMissingStatus imu_missing_status = 2;
  bool has_imu_missing_status() const;
  void clear_imu_missing_status();
  static const int kImuMissingStatusFieldNumber = 2;
  ::apollo::localization::ImuMsgMissingStatus imu_missing_status() const;
  void set_imu_missing_status(::apollo::localization::ImuMsgMissingStatus value);

  // optional .apollo.localization.ImuMsgDataStatus imu_data_status = 3;
  bool has_imu_data_status() const;
  void clear_imu_data_status();
  static const int kImuDataStatusFieldNumber = 3;
  ::apollo::localization::ImuMsgDataStatus imu_data_status() const;
  void set_imu_data_status(::apollo::localization::ImuMsgDataStatus value);

  // @@protoc_insertion_point(class_scope:apollo.localization.MsfSensorMsgStatus)
 private:
  void set_has_imu_delay_status();
  void clear_has_imu_delay_status();
  void set_has_imu_missing_status();
  void clear_has_imu_missing_status();
  void set_has_imu_data_status();
  void clear_has_imu_data_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  int imu_delay_status_;
  int imu_missing_status_;
  int imu_data_status_;
  friend struct protobuf_modules_2fcommon_5fmsgs_2flocalization_5fmsgs_2flocalization_5fstatus_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MsfGnssMapOffset : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.localization.MsfGnssMapOffset) */ {
 public:
  MsfGnssMapOffset();
  virtual ~MsfGnssMapOffset();

  MsfGnssMapOffset(const MsfGnssMapOffset& from);

  inline MsfGnssMapOffset& operator=(const MsfGnssMapOffset& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MsfGnssMapOffset(MsfGnssMapOffset&& from) noexcept
    : MsfGnssMapOffset() {
    *this = ::std::move(from);
  }

  inline MsfGnssMapOffset& operator=(MsfGnssMapOffset&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsfGnssMapOffset& default_instance();

  static inline const MsfGnssMapOffset* internal_default_instance() {
    return reinterpret_cast<const MsfGnssMapOffset*>(
               &_MsfGnssMapOffset_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(MsfGnssMapOffset* other);
  friend void swap(MsfGnssMapOffset& a, MsfGnssMapOffset& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MsfGnssMapOffset* New() const PROTOBUF_FINAL { return New(NULL); }

  MsfGnssMapOffset* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MsfGnssMapOffset& from);
  void MergeFrom(const MsfGnssMapOffset& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MsfGnssMapOffset* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double offsetx = 2;
  bool has_offsetx() const;
  void clear_offsetx();
  static const int kOffsetxFieldNumber = 2;
  double offsetx() const;
  void set_offsetx(double value);

  // optional double offsety = 3;
  bool has_offsety() const;
  void clear_offsety();
  static const int kOffsetyFieldNumber = 3;
  double offsety() const;
  void set_offsety(double value);

  // optional .apollo.localization.MsfGnssMapOffsetStatus status = 1;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::apollo::localization::MsfGnssMapOffsetStatus status() const;
  void set_status(::apollo::localization::MsfGnssMapOffsetStatus value);

  // @@protoc_insertion_point(class_scope:apollo.localization.MsfGnssMapOffset)
 private:
  void set_has_status();
  void clear_has_status();
  void set_has_offsetx();
  void clear_has_offsetx();
  void set_has_offsety();
  void clear_has_offsety();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double offsetx_;
  double offsety_;
  int status_;
  friend struct protobuf_modules_2fcommon_5fmsgs_2flocalization_5fmsgs_2flocalization_5fstatus_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MsfInitDetails : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.localization.MsfInitDetails) */ {
 public:
  MsfInitDetails();
  virtual ~MsfInitDetails();

  MsfInitDetails(const MsfInitDetails& from);

  inline MsfInitDetails& operator=(const MsfInitDetails& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MsfInitDetails(MsfInitDetails&& from) noexcept
    : MsfInitDetails() {
    *this = ::std::move(from);
  }

  inline MsfInitDetails& operator=(MsfInitDetails&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsfInitDetails& default_instance();

  static inline const MsfInitDetails* internal_default_instance() {
    return reinterpret_cast<const MsfInitDetails*>(
               &_MsfInitDetails_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(MsfInitDetails* other);
  friend void swap(MsfInitDetails& a, MsfInitDetails& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MsfInitDetails* New() const PROTOBUF_FINAL { return New(NULL); }

  MsfInitDetails* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MsfInitDetails& from);
  void MergeFrom(const MsfInitDetails& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MsfInitDetails* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.localization.MsfInitPoseSource init_pose_source = 1;
  bool has_init_pose_source() const;
  void clear_init_pose_source();
  static const int kInitPoseSourceFieldNumber = 1;
  ::apollo::localization::MsfInitPoseSource init_pose_source() const;
  void set_init_pose_source(::apollo::localization::MsfInitPoseSource value);

  // optional .apollo.localization.MsfInitPoseStatus local_search_from_integpva_status = 2;
  bool has_local_search_from_integpva_status() const;
  void clear_local_search_from_integpva_status();
  static const int kLocalSearchFromIntegpvaStatusFieldNumber = 2;
  ::apollo::localization::MsfInitPoseStatus local_search_from_integpva_status() const;
  void set_local_search_from_integpva_status(::apollo::localization::MsfInitPoseStatus value);

  // optional .apollo.localization.MsfInitPoseStatus local_search_from_file_status = 3;
  bool has_local_search_from_file_status() const;
  void clear_local_search_from_file_status();
  static const int kLocalSearchFromFileStatusFieldNumber = 3;
  ::apollo::localization::MsfInitPoseStatus local_search_from_file_status() const;
  void set_local_search_from_file_status(::apollo::localization::MsfInitPoseStatus value);

  // optional .apollo.localization.MsfInitPoseStatus local_update_from_file_status = 4;
  bool has_local_update_from_file_status() const;
  void clear_local_update_from_file_status();
  static const int kLocalUpdateFromFileStatusFieldNumber = 4;
  ::apollo::localization::MsfInitPoseStatus local_update_from_file_status() const;
  void set_local_update_from_file_status(::apollo::localization::MsfInitPoseStatus value);

  // optional .apollo.localization.MsfInitPoseStatus user_interaction_status = 5;
  bool has_user_interaction_status() const;
  void clear_user_interaction_status();
  static const int kUserInteractionStatusFieldNumber = 5;
  ::apollo::localization::MsfInitPoseStatus user_interaction_status() const;
  void set_user_interaction_status(::apollo::localization::MsfInitPoseStatus value);

  // optional int32 gnss_position_type = 6;
  bool has_gnss_position_type() const;
  void clear_gnss_position_type();
  static const int kGnssPositionTypeFieldNumber = 6;
  ::google::protobuf::int32 gnss_position_type() const;
  void set_gnss_position_type(::google::protobuf::int32 value);

  // optional .apollo.localization.MsfInitPoseStatus local_from_global_lidar_status = 7;
  bool has_local_from_global_lidar_status() const;
  void clear_local_from_global_lidar_status();
  static const int kLocalFromGlobalLidarStatusFieldNumber = 7;
  ::apollo::localization::MsfInitPoseStatus local_from_global_lidar_status() const;
  void set_local_from_global_lidar_status(::apollo::localization::MsfInitPoseStatus value);

  // @@protoc_insertion_point(class_scope:apollo.localization.MsfInitDetails)
 private:
  void set_has_init_pose_source();
  void clear_has_init_pose_source();
  void set_has_local_search_from_integpva_status();
  void clear_has_local_search_from_integpva_status();
  void set_has_local_search_from_file_status();
  void clear_has_local_search_from_file_status();
  void set_has_local_update_from_file_status();
  void clear_has_local_update_from_file_status();
  void set_has_user_interaction_status();
  void clear_has_user_interaction_status();
  void set_has_gnss_position_type();
  void clear_has_gnss_position_type();
  void set_has_local_from_global_lidar_status();
  void clear_has_local_from_global_lidar_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  int init_pose_source_;
  int local_search_from_integpva_status_;
  int local_search_from_file_status_;
  int local_update_from_file_status_;
  int user_interaction_status_;
  ::google::protobuf::int32 gnss_position_type_;
  int local_from_global_lidar_status_;
  friend struct protobuf_modules_2fcommon_5fmsgs_2flocalization_5fmsgs_2flocalization_5fstatus_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MsfStatus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.localization.MsfStatus) */ {
 public:
  MsfStatus();
  virtual ~MsfStatus();

  MsfStatus(const MsfStatus& from);

  inline MsfStatus& operator=(const MsfStatus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MsfStatus(MsfStatus&& from) noexcept
    : MsfStatus() {
    *this = ::std::move(from);
  }

  inline MsfStatus& operator=(MsfStatus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsfStatus& default_instance();

  static inline const MsfStatus* internal_default_instance() {
    return reinterpret_cast<const MsfStatus*>(
               &_MsfStatus_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(MsfStatus* other);
  friend void swap(MsfStatus& a, MsfStatus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MsfStatus* New() const PROTOBUF_FINAL { return New(NULL); }

  MsfStatus* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MsfStatus& from);
  void MergeFrom(const MsfStatus& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MsfStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.localization.MsfInitDetails msf_init_details = 8;
  bool has_msf_init_details() const;
  void clear_msf_init_details();
  static const int kMsfInitDetailsFieldNumber = 8;
  const ::apollo::localization::MsfInitDetails& msf_init_details() const;
  ::apollo::localization::MsfInitDetails* mutable_msf_init_details();
  ::apollo::localization::MsfInitDetails* release_msf_init_details();
  void set_allocated_msf_init_details(::apollo::localization::MsfInitDetails* msf_init_details);

  // optional .apollo.localization.MsfGnssMapOffset gnss_map_offset = 10;
  bool has_gnss_map_offset() const;
  void clear_gnss_map_offset();
  static const int kGnssMapOffsetFieldNumber = 10;
  const ::apollo::localization::MsfGnssMapOffset& gnss_map_offset() const;
  ::apollo::localization::MsfGnssMapOffset* mutable_gnss_map_offset();
  ::apollo::localization::MsfGnssMapOffset* release_gnss_map_offset();
  void set_allocated_gnss_map_offset(::apollo::localization::MsfGnssMapOffset* gnss_map_offset);

  // optional .apollo.localization.LocalLidarConsistency local_lidar_consistency = 1;
  bool has_local_lidar_consistency() const;
  void clear_local_lidar_consistency();
  static const int kLocalLidarConsistencyFieldNumber = 1;
  ::apollo::localization::LocalLidarConsistency local_lidar_consistency() const;
  void set_local_lidar_consistency(::apollo::localization::LocalLidarConsistency value);

  // optional .apollo.localization.GnssConsistency gnss_consistency = 2;
  bool has_gnss_consistency() const;
  void clear_gnss_consistency();
  static const int kGnssConsistencyFieldNumber = 2;
  ::apollo::localization::GnssConsistency gnss_consistency() const;
  void set_gnss_consistency(::apollo::localization::GnssConsistency value);

  // optional .apollo.localization.LocalLidarStatus local_lidar_status = 3;
  bool has_local_lidar_status() const;
  void clear_local_lidar_status();
  static const int kLocalLidarStatusFieldNumber = 3;
  ::apollo::localization::LocalLidarStatus local_lidar_status() const;
  void set_local_lidar_status(::apollo::localization::LocalLidarStatus value);

  // optional .apollo.localization.GnssPositionType gnsspos_position_type = 4;
  bool has_gnsspos_position_type() const;
  void clear_gnsspos_position_type();
  static const int kGnssposPositionTypeFieldNumber = 4;
  ::apollo::localization::GnssPositionType gnsspos_position_type() const;
  void set_gnsspos_position_type(::apollo::localization::GnssPositionType value);

  // optional uint32 heading_position_type = 5;
  bool has_heading_position_type() const;
  void clear_heading_position_type();
  static const int kHeadingPositionTypeFieldNumber = 5;
  ::google::protobuf::uint32 heading_position_type() const;
  void set_heading_position_type(::google::protobuf::uint32 value);

  // optional .apollo.localization.MSFInitStatus msf_init_status = 6;
  bool has_msf_init_status() const;
  void clear_msf_init_status();
  static const int kMsfInitStatusFieldNumber = 6;
  ::apollo::localization::MSFInitStatus msf_init_status() const;
  void set_msf_init_status(::apollo::localization::MSFInitStatus value);

  // optional .apollo.localization.MsfRunningStatus msf_running_status = 7;
  bool has_msf_running_status() const;
  void clear_msf_running_status();
  static const int kMsfRunningStatusFieldNumber = 7;
  ::apollo::localization::MsfRunningStatus msf_running_status() const;
  void set_msf_running_status(::apollo::localization::MsfRunningStatus value);

  // optional .apollo.localization.LocalLidarQuality local_lidar_quality = 9;
  bool has_local_lidar_quality() const;
  void clear_local_lidar_quality();
  static const int kLocalLidarQualityFieldNumber = 9;
  ::apollo::localization::LocalLidarQuality local_lidar_quality() const;
  void set_local_lidar_quality(::apollo::localization::LocalLidarQuality value);

  // optional double local_lidar_score = 12;
  bool has_local_lidar_score() const;
  void clear_local_lidar_score();
  static const int kLocalLidarScoreFieldNumber = 12;
  double local_lidar_score() const;
  void set_local_lidar_score(double value);

  // optional bool lidar_alt_from_map = 11;
  bool has_lidar_alt_from_map() const;
  void clear_lidar_alt_from_map();
  static const int kLidarAltFromMapFieldNumber = 11;
  bool lidar_alt_from_map() const;
  void set_lidar_alt_from_map(bool value);

  // optional bool local_reliability_status = 13 [default = false];
  bool has_local_reliability_status() const;
  void clear_local_reliability_status();
  static const int kLocalReliabilityStatusFieldNumber = 13;
  bool local_reliability_status() const;
  void set_local_reliability_status(bool value);

  // @@protoc_insertion_point(class_scope:apollo.localization.MsfStatus)
 private:
  void set_has_local_lidar_consistency();
  void clear_has_local_lidar_consistency();
  void set_has_gnss_consistency();
  void clear_has_gnss_consistency();
  void set_has_local_lidar_status();
  void clear_has_local_lidar_status();
  void set_has_gnsspos_position_type();
  void clear_has_gnsspos_position_type();
  void set_has_heading_position_type();
  void clear_has_heading_position_type();
  void set_has_msf_init_status();
  void clear_has_msf_init_status();
  void set_has_msf_running_status();
  void clear_has_msf_running_status();
  void set_has_msf_init_details();
  void clear_has_msf_init_details();
  void set_has_local_lidar_quality();
  void clear_has_local_lidar_quality();
  void set_has_gnss_map_offset();
  void clear_has_gnss_map_offset();
  void set_has_lidar_alt_from_map();
  void clear_has_lidar_alt_from_map();
  void set_has_local_lidar_score();
  void clear_has_local_lidar_score();
  void set_has_local_reliability_status();
  void clear_has_local_reliability_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::apollo::localization::MsfInitDetails* msf_init_details_;
  ::apollo::localization::MsfGnssMapOffset* gnss_map_offset_;
  int local_lidar_consistency_;
  int gnss_consistency_;
  int local_lidar_status_;
  int gnsspos_position_type_;
  ::google::protobuf::uint32 heading_position_type_;
  int msf_init_status_;
  int msf_running_status_;
  int local_lidar_quality_;
  double local_lidar_score_;
  bool lidar_alt_from_map_;
  bool local_reliability_status_;
  friend struct protobuf_modules_2fcommon_5fmsgs_2flocalization_5fmsgs_2flocalization_5fstatus_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MsfSensorMsgStatus

// optional .apollo.localization.ImuMsgDelayStatus imu_delay_status = 1;
inline bool MsfSensorMsgStatus::has_imu_delay_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsfSensorMsgStatus::set_has_imu_delay_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsfSensorMsgStatus::clear_has_imu_delay_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsfSensorMsgStatus::clear_imu_delay_status() {
  imu_delay_status_ = 0;
  clear_has_imu_delay_status();
}
inline ::apollo::localization::ImuMsgDelayStatus MsfSensorMsgStatus::imu_delay_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfSensorMsgStatus.imu_delay_status)
  return static_cast< ::apollo::localization::ImuMsgDelayStatus >(imu_delay_status_);
}
inline void MsfSensorMsgStatus::set_imu_delay_status(::apollo::localization::ImuMsgDelayStatus value) {
  assert(::apollo::localization::ImuMsgDelayStatus_IsValid(value));
  set_has_imu_delay_status();
  imu_delay_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfSensorMsgStatus.imu_delay_status)
}

// optional .apollo.localization.ImuMsgMissingStatus imu_missing_status = 2;
inline bool MsfSensorMsgStatus::has_imu_missing_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsfSensorMsgStatus::set_has_imu_missing_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsfSensorMsgStatus::clear_has_imu_missing_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsfSensorMsgStatus::clear_imu_missing_status() {
  imu_missing_status_ = 0;
  clear_has_imu_missing_status();
}
inline ::apollo::localization::ImuMsgMissingStatus MsfSensorMsgStatus::imu_missing_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfSensorMsgStatus.imu_missing_status)
  return static_cast< ::apollo::localization::ImuMsgMissingStatus >(imu_missing_status_);
}
inline void MsfSensorMsgStatus::set_imu_missing_status(::apollo::localization::ImuMsgMissingStatus value) {
  assert(::apollo::localization::ImuMsgMissingStatus_IsValid(value));
  set_has_imu_missing_status();
  imu_missing_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfSensorMsgStatus.imu_missing_status)
}

// optional .apollo.localization.ImuMsgDataStatus imu_data_status = 3;
inline bool MsfSensorMsgStatus::has_imu_data_status() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsfSensorMsgStatus::set_has_imu_data_status() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsfSensorMsgStatus::clear_has_imu_data_status() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsfSensorMsgStatus::clear_imu_data_status() {
  imu_data_status_ = 0;
  clear_has_imu_data_status();
}
inline ::apollo::localization::ImuMsgDataStatus MsfSensorMsgStatus::imu_data_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfSensorMsgStatus.imu_data_status)
  return static_cast< ::apollo::localization::ImuMsgDataStatus >(imu_data_status_);
}
inline void MsfSensorMsgStatus::set_imu_data_status(::apollo::localization::ImuMsgDataStatus value) {
  assert(::apollo::localization::ImuMsgDataStatus_IsValid(value));
  set_has_imu_data_status();
  imu_data_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfSensorMsgStatus.imu_data_status)
}

// -------------------------------------------------------------------

// MsfGnssMapOffset

// optional .apollo.localization.MsfGnssMapOffsetStatus status = 1;
inline bool MsfGnssMapOffset::has_status() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsfGnssMapOffset::set_has_status() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsfGnssMapOffset::clear_has_status() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsfGnssMapOffset::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::apollo::localization::MsfGnssMapOffsetStatus MsfGnssMapOffset::status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfGnssMapOffset.status)
  return static_cast< ::apollo::localization::MsfGnssMapOffsetStatus >(status_);
}
inline void MsfGnssMapOffset::set_status(::apollo::localization::MsfGnssMapOffsetStatus value) {
  assert(::apollo::localization::MsfGnssMapOffsetStatus_IsValid(value));
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfGnssMapOffset.status)
}

// optional double offsetx = 2;
inline bool MsfGnssMapOffset::has_offsetx() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsfGnssMapOffset::set_has_offsetx() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsfGnssMapOffset::clear_has_offsetx() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsfGnssMapOffset::clear_offsetx() {
  offsetx_ = 0;
  clear_has_offsetx();
}
inline double MsfGnssMapOffset::offsetx() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfGnssMapOffset.offsetx)
  return offsetx_;
}
inline void MsfGnssMapOffset::set_offsetx(double value) {
  set_has_offsetx();
  offsetx_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfGnssMapOffset.offsetx)
}

// optional double offsety = 3;
inline bool MsfGnssMapOffset::has_offsety() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsfGnssMapOffset::set_has_offsety() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsfGnssMapOffset::clear_has_offsety() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsfGnssMapOffset::clear_offsety() {
  offsety_ = 0;
  clear_has_offsety();
}
inline double MsfGnssMapOffset::offsety() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfGnssMapOffset.offsety)
  return offsety_;
}
inline void MsfGnssMapOffset::set_offsety(double value) {
  set_has_offsety();
  offsety_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfGnssMapOffset.offsety)
}

// -------------------------------------------------------------------

// MsfInitDetails

// optional .apollo.localization.MsfInitPoseSource init_pose_source = 1;
inline bool MsfInitDetails::has_init_pose_source() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsfInitDetails::set_has_init_pose_source() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsfInitDetails::clear_has_init_pose_source() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsfInitDetails::clear_init_pose_source() {
  init_pose_source_ = 0;
  clear_has_init_pose_source();
}
inline ::apollo::localization::MsfInitPoseSource MsfInitDetails::init_pose_source() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfInitDetails.init_pose_source)
  return static_cast< ::apollo::localization::MsfInitPoseSource >(init_pose_source_);
}
inline void MsfInitDetails::set_init_pose_source(::apollo::localization::MsfInitPoseSource value) {
  assert(::apollo::localization::MsfInitPoseSource_IsValid(value));
  set_has_init_pose_source();
  init_pose_source_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfInitDetails.init_pose_source)
}

// optional .apollo.localization.MsfInitPoseStatus local_search_from_integpva_status = 2;
inline bool MsfInitDetails::has_local_search_from_integpva_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsfInitDetails::set_has_local_search_from_integpva_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsfInitDetails::clear_has_local_search_from_integpva_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsfInitDetails::clear_local_search_from_integpva_status() {
  local_search_from_integpva_status_ = 0;
  clear_has_local_search_from_integpva_status();
}
inline ::apollo::localization::MsfInitPoseStatus MsfInitDetails::local_search_from_integpva_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfInitDetails.local_search_from_integpva_status)
  return static_cast< ::apollo::localization::MsfInitPoseStatus >(local_search_from_integpva_status_);
}
inline void MsfInitDetails::set_local_search_from_integpva_status(::apollo::localization::MsfInitPoseStatus value) {
  assert(::apollo::localization::MsfInitPoseStatus_IsValid(value));
  set_has_local_search_from_integpva_status();
  local_search_from_integpva_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfInitDetails.local_search_from_integpva_status)
}

// optional .apollo.localization.MsfInitPoseStatus local_search_from_file_status = 3;
inline bool MsfInitDetails::has_local_search_from_file_status() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsfInitDetails::set_has_local_search_from_file_status() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsfInitDetails::clear_has_local_search_from_file_status() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsfInitDetails::clear_local_search_from_file_status() {
  local_search_from_file_status_ = 0;
  clear_has_local_search_from_file_status();
}
inline ::apollo::localization::MsfInitPoseStatus MsfInitDetails::local_search_from_file_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfInitDetails.local_search_from_file_status)
  return static_cast< ::apollo::localization::MsfInitPoseStatus >(local_search_from_file_status_);
}
inline void MsfInitDetails::set_local_search_from_file_status(::apollo::localization::MsfInitPoseStatus value) {
  assert(::apollo::localization::MsfInitPoseStatus_IsValid(value));
  set_has_local_search_from_file_status();
  local_search_from_file_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfInitDetails.local_search_from_file_status)
}

// optional .apollo.localization.MsfInitPoseStatus local_update_from_file_status = 4;
inline bool MsfInitDetails::has_local_update_from_file_status() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsfInitDetails::set_has_local_update_from_file_status() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsfInitDetails::clear_has_local_update_from_file_status() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsfInitDetails::clear_local_update_from_file_status() {
  local_update_from_file_status_ = 0;
  clear_has_local_update_from_file_status();
}
inline ::apollo::localization::MsfInitPoseStatus MsfInitDetails::local_update_from_file_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfInitDetails.local_update_from_file_status)
  return static_cast< ::apollo::localization::MsfInitPoseStatus >(local_update_from_file_status_);
}
inline void MsfInitDetails::set_local_update_from_file_status(::apollo::localization::MsfInitPoseStatus value) {
  assert(::apollo::localization::MsfInitPoseStatus_IsValid(value));
  set_has_local_update_from_file_status();
  local_update_from_file_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfInitDetails.local_update_from_file_status)
}

// optional .apollo.localization.MsfInitPoseStatus user_interaction_status = 5;
inline bool MsfInitDetails::has_user_interaction_status() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsfInitDetails::set_has_user_interaction_status() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsfInitDetails::clear_has_user_interaction_status() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsfInitDetails::clear_user_interaction_status() {
  user_interaction_status_ = 0;
  clear_has_user_interaction_status();
}
inline ::apollo::localization::MsfInitPoseStatus MsfInitDetails::user_interaction_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfInitDetails.user_interaction_status)
  return static_cast< ::apollo::localization::MsfInitPoseStatus >(user_interaction_status_);
}
inline void MsfInitDetails::set_user_interaction_status(::apollo::localization::MsfInitPoseStatus value) {
  assert(::apollo::localization::MsfInitPoseStatus_IsValid(value));
  set_has_user_interaction_status();
  user_interaction_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfInitDetails.user_interaction_status)
}

// optional int32 gnss_position_type = 6;
inline bool MsfInitDetails::has_gnss_position_type() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MsfInitDetails::set_has_gnss_position_type() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MsfInitDetails::clear_has_gnss_position_type() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MsfInitDetails::clear_gnss_position_type() {
  gnss_position_type_ = 0;
  clear_has_gnss_position_type();
}
inline ::google::protobuf::int32 MsfInitDetails::gnss_position_type() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfInitDetails.gnss_position_type)
  return gnss_position_type_;
}
inline void MsfInitDetails::set_gnss_position_type(::google::protobuf::int32 value) {
  set_has_gnss_position_type();
  gnss_position_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfInitDetails.gnss_position_type)
}

// optional .apollo.localization.MsfInitPoseStatus local_from_global_lidar_status = 7;
inline bool MsfInitDetails::has_local_from_global_lidar_status() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MsfInitDetails::set_has_local_from_global_lidar_status() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MsfInitDetails::clear_has_local_from_global_lidar_status() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MsfInitDetails::clear_local_from_global_lidar_status() {
  local_from_global_lidar_status_ = 0;
  clear_has_local_from_global_lidar_status();
}
inline ::apollo::localization::MsfInitPoseStatus MsfInitDetails::local_from_global_lidar_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfInitDetails.local_from_global_lidar_status)
  return static_cast< ::apollo::localization::MsfInitPoseStatus >(local_from_global_lidar_status_);
}
inline void MsfInitDetails::set_local_from_global_lidar_status(::apollo::localization::MsfInitPoseStatus value) {
  assert(::apollo::localization::MsfInitPoseStatus_IsValid(value));
  set_has_local_from_global_lidar_status();
  local_from_global_lidar_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfInitDetails.local_from_global_lidar_status)
}

// -------------------------------------------------------------------

// MsfStatus

// optional .apollo.localization.LocalLidarConsistency local_lidar_consistency = 1;
inline bool MsfStatus::has_local_lidar_consistency() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsfStatus::set_has_local_lidar_consistency() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsfStatus::clear_has_local_lidar_consistency() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsfStatus::clear_local_lidar_consistency() {
  local_lidar_consistency_ = 0;
  clear_has_local_lidar_consistency();
}
inline ::apollo::localization::LocalLidarConsistency MsfStatus::local_lidar_consistency() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.local_lidar_consistency)
  return static_cast< ::apollo::localization::LocalLidarConsistency >(local_lidar_consistency_);
}
inline void MsfStatus::set_local_lidar_consistency(::apollo::localization::LocalLidarConsistency value) {
  assert(::apollo::localization::LocalLidarConsistency_IsValid(value));
  set_has_local_lidar_consistency();
  local_lidar_consistency_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfStatus.local_lidar_consistency)
}

// optional .apollo.localization.GnssConsistency gnss_consistency = 2;
inline bool MsfStatus::has_gnss_consistency() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsfStatus::set_has_gnss_consistency() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsfStatus::clear_has_gnss_consistency() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsfStatus::clear_gnss_consistency() {
  gnss_consistency_ = 0;
  clear_has_gnss_consistency();
}
inline ::apollo::localization::GnssConsistency MsfStatus::gnss_consistency() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.gnss_consistency)
  return static_cast< ::apollo::localization::GnssConsistency >(gnss_consistency_);
}
inline void MsfStatus::set_gnss_consistency(::apollo::localization::GnssConsistency value) {
  assert(::apollo::localization::GnssConsistency_IsValid(value));
  set_has_gnss_consistency();
  gnss_consistency_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfStatus.gnss_consistency)
}

// optional .apollo.localization.LocalLidarStatus local_lidar_status = 3;
inline bool MsfStatus::has_local_lidar_status() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsfStatus::set_has_local_lidar_status() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsfStatus::clear_has_local_lidar_status() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsfStatus::clear_local_lidar_status() {
  local_lidar_status_ = 0;
  clear_has_local_lidar_status();
}
inline ::apollo::localization::LocalLidarStatus MsfStatus::local_lidar_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.local_lidar_status)
  return static_cast< ::apollo::localization::LocalLidarStatus >(local_lidar_status_);
}
inline void MsfStatus::set_local_lidar_status(::apollo::localization::LocalLidarStatus value) {
  assert(::apollo::localization::LocalLidarStatus_IsValid(value));
  set_has_local_lidar_status();
  local_lidar_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfStatus.local_lidar_status)
}

// optional .apollo.localization.GnssPositionType gnsspos_position_type = 4;
inline bool MsfStatus::has_gnsspos_position_type() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MsfStatus::set_has_gnsspos_position_type() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MsfStatus::clear_has_gnsspos_position_type() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MsfStatus::clear_gnsspos_position_type() {
  gnsspos_position_type_ = 0;
  clear_has_gnsspos_position_type();
}
inline ::apollo::localization::GnssPositionType MsfStatus::gnsspos_position_type() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.gnsspos_position_type)
  return static_cast< ::apollo::localization::GnssPositionType >(gnsspos_position_type_);
}
inline void MsfStatus::set_gnsspos_position_type(::apollo::localization::GnssPositionType value) {
  assert(::apollo::localization::GnssPositionType_IsValid(value));
  set_has_gnsspos_position_type();
  gnsspos_position_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfStatus.gnsspos_position_type)
}

// optional uint32 heading_position_type = 5;
inline bool MsfStatus::has_heading_position_type() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MsfStatus::set_has_heading_position_type() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MsfStatus::clear_has_heading_position_type() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MsfStatus::clear_heading_position_type() {
  heading_position_type_ = 0u;
  clear_has_heading_position_type();
}
inline ::google::protobuf::uint32 MsfStatus::heading_position_type() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.heading_position_type)
  return heading_position_type_;
}
inline void MsfStatus::set_heading_position_type(::google::protobuf::uint32 value) {
  set_has_heading_position_type();
  heading_position_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfStatus.heading_position_type)
}

// optional .apollo.localization.MSFInitStatus msf_init_status = 6;
inline bool MsfStatus::has_msf_init_status() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void MsfStatus::set_has_msf_init_status() {
  _has_bits_[0] |= 0x00000080u;
}
inline void MsfStatus::clear_has_msf_init_status() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void MsfStatus::clear_msf_init_status() {
  msf_init_status_ = 0;
  clear_has_msf_init_status();
}
inline ::apollo::localization::MSFInitStatus MsfStatus::msf_init_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.msf_init_status)
  return static_cast< ::apollo::localization::MSFInitStatus >(msf_init_status_);
}
inline void MsfStatus::set_msf_init_status(::apollo::localization::MSFInitStatus value) {
  assert(::apollo::localization::MSFInitStatus_IsValid(value));
  set_has_msf_init_status();
  msf_init_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfStatus.msf_init_status)
}

// optional .apollo.localization.MsfRunningStatus msf_running_status = 7;
inline bool MsfStatus::has_msf_running_status() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void MsfStatus::set_has_msf_running_status() {
  _has_bits_[0] |= 0x00000100u;
}
inline void MsfStatus::clear_has_msf_running_status() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void MsfStatus::clear_msf_running_status() {
  msf_running_status_ = 0;
  clear_has_msf_running_status();
}
inline ::apollo::localization::MsfRunningStatus MsfStatus::msf_running_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.msf_running_status)
  return static_cast< ::apollo::localization::MsfRunningStatus >(msf_running_status_);
}
inline void MsfStatus::set_msf_running_status(::apollo::localization::MsfRunningStatus value) {
  assert(::apollo::localization::MsfRunningStatus_IsValid(value));
  set_has_msf_running_status();
  msf_running_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfStatus.msf_running_status)
}

// optional .apollo.localization.MsfInitDetails msf_init_details = 8;
inline bool MsfStatus::has_msf_init_details() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsfStatus::set_has_msf_init_details() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsfStatus::clear_has_msf_init_details() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsfStatus::clear_msf_init_details() {
  if (msf_init_details_ != NULL) msf_init_details_->::apollo::localization::MsfInitDetails::Clear();
  clear_has_msf_init_details();
}
inline const ::apollo::localization::MsfInitDetails& MsfStatus::msf_init_details() const {
  const ::apollo::localization::MsfInitDetails* p = msf_init_details_;
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.msf_init_details)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::localization::MsfInitDetails*>(
      &::apollo::localization::_MsfInitDetails_default_instance_);
}
inline ::apollo::localization::MsfInitDetails* MsfStatus::mutable_msf_init_details() {
  set_has_msf_init_details();
  if (msf_init_details_ == NULL) {
    msf_init_details_ = new ::apollo::localization::MsfInitDetails;
  }
  // @@protoc_insertion_point(field_mutable:apollo.localization.MsfStatus.msf_init_details)
  return msf_init_details_;
}
inline ::apollo::localization::MsfInitDetails* MsfStatus::release_msf_init_details() {
  // @@protoc_insertion_point(field_release:apollo.localization.MsfStatus.msf_init_details)
  clear_has_msf_init_details();
  ::apollo::localization::MsfInitDetails* temp = msf_init_details_;
  msf_init_details_ = NULL;
  return temp;
}
inline void MsfStatus::set_allocated_msf_init_details(::apollo::localization::MsfInitDetails* msf_init_details) {
  delete msf_init_details_;
  msf_init_details_ = msf_init_details;
  if (msf_init_details) {
    set_has_msf_init_details();
  } else {
    clear_has_msf_init_details();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.MsfStatus.msf_init_details)
}

// optional .apollo.localization.LocalLidarQuality local_lidar_quality = 9;
inline bool MsfStatus::has_local_lidar_quality() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void MsfStatus::set_has_local_lidar_quality() {
  _has_bits_[0] |= 0x00000200u;
}
inline void MsfStatus::clear_has_local_lidar_quality() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void MsfStatus::clear_local_lidar_quality() {
  local_lidar_quality_ = 0;
  clear_has_local_lidar_quality();
}
inline ::apollo::localization::LocalLidarQuality MsfStatus::local_lidar_quality() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.local_lidar_quality)
  return static_cast< ::apollo::localization::LocalLidarQuality >(local_lidar_quality_);
}
inline void MsfStatus::set_local_lidar_quality(::apollo::localization::LocalLidarQuality value) {
  assert(::apollo::localization::LocalLidarQuality_IsValid(value));
  set_has_local_lidar_quality();
  local_lidar_quality_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfStatus.local_lidar_quality)
}

// optional .apollo.localization.MsfGnssMapOffset gnss_map_offset = 10;
inline bool MsfStatus::has_gnss_map_offset() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsfStatus::set_has_gnss_map_offset() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsfStatus::clear_has_gnss_map_offset() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsfStatus::clear_gnss_map_offset() {
  if (gnss_map_offset_ != NULL) gnss_map_offset_->::apollo::localization::MsfGnssMapOffset::Clear();
  clear_has_gnss_map_offset();
}
inline const ::apollo::localization::MsfGnssMapOffset& MsfStatus::gnss_map_offset() const {
  const ::apollo::localization::MsfGnssMapOffset* p = gnss_map_offset_;
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.gnss_map_offset)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::localization::MsfGnssMapOffset*>(
      &::apollo::localization::_MsfGnssMapOffset_default_instance_);
}
inline ::apollo::localization::MsfGnssMapOffset* MsfStatus::mutable_gnss_map_offset() {
  set_has_gnss_map_offset();
  if (gnss_map_offset_ == NULL) {
    gnss_map_offset_ = new ::apollo::localization::MsfGnssMapOffset;
  }
  // @@protoc_insertion_point(field_mutable:apollo.localization.MsfStatus.gnss_map_offset)
  return gnss_map_offset_;
}
inline ::apollo::localization::MsfGnssMapOffset* MsfStatus::release_gnss_map_offset() {
  // @@protoc_insertion_point(field_release:apollo.localization.MsfStatus.gnss_map_offset)
  clear_has_gnss_map_offset();
  ::apollo::localization::MsfGnssMapOffset* temp = gnss_map_offset_;
  gnss_map_offset_ = NULL;
  return temp;
}
inline void MsfStatus::set_allocated_gnss_map_offset(::apollo::localization::MsfGnssMapOffset* gnss_map_offset) {
  delete gnss_map_offset_;
  gnss_map_offset_ = gnss_map_offset;
  if (gnss_map_offset) {
    set_has_gnss_map_offset();
  } else {
    clear_has_gnss_map_offset();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.MsfStatus.gnss_map_offset)
}

// optional bool lidar_alt_from_map = 11;
inline bool MsfStatus::has_lidar_alt_from_map() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void MsfStatus::set_has_lidar_alt_from_map() {
  _has_bits_[0] |= 0x00000800u;
}
inline void MsfStatus::clear_has_lidar_alt_from_map() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void MsfStatus::clear_lidar_alt_from_map() {
  lidar_alt_from_map_ = false;
  clear_has_lidar_alt_from_map();
}
inline bool MsfStatus::lidar_alt_from_map() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.lidar_alt_from_map)
  return lidar_alt_from_map_;
}
inline void MsfStatus::set_lidar_alt_from_map(bool value) {
  set_has_lidar_alt_from_map();
  lidar_alt_from_map_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfStatus.lidar_alt_from_map)
}

// optional double local_lidar_score = 12;
inline bool MsfStatus::has_local_lidar_score() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void MsfStatus::set_has_local_lidar_score() {
  _has_bits_[0] |= 0x00000400u;
}
inline void MsfStatus::clear_has_local_lidar_score() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void MsfStatus::clear_local_lidar_score() {
  local_lidar_score_ = 0;
  clear_has_local_lidar_score();
}
inline double MsfStatus::local_lidar_score() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.local_lidar_score)
  return local_lidar_score_;
}
inline void MsfStatus::set_local_lidar_score(double value) {
  set_has_local_lidar_score();
  local_lidar_score_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfStatus.local_lidar_score)
}

// optional bool local_reliability_status = 13 [default = false];
inline bool MsfStatus::has_local_reliability_status() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void MsfStatus::set_has_local_reliability_status() {
  _has_bits_[0] |= 0x00001000u;
}
inline void MsfStatus::clear_has_local_reliability_status() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void MsfStatus::clear_local_reliability_status() {
  local_reliability_status_ = false;
  clear_has_local_reliability_status();
}
inline bool MsfStatus::local_reliability_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.MsfStatus.local_reliability_status)
  return local_reliability_status_;
}
inline void MsfStatus::set_local_reliability_status(bool value) {
  set_has_local_reliability_status();
  local_reliability_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.MsfStatus.local_reliability_status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace localization
}  // namespace apollo

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::localization::LocalLidarStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::LocalLidarStatus>() {
  return ::apollo::localization::LocalLidarStatus_descriptor();
}
template <> struct is_proto_enum< ::apollo::localization::LocalLidarQuality> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::LocalLidarQuality>() {
  return ::apollo::localization::LocalLidarQuality_descriptor();
}
template <> struct is_proto_enum< ::apollo::localization::LocalLidarConsistency> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::LocalLidarConsistency>() {
  return ::apollo::localization::LocalLidarConsistency_descriptor();
}
template <> struct is_proto_enum< ::apollo::localization::GnssConsistency> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::GnssConsistency>() {
  return ::apollo::localization::GnssConsistency_descriptor();
}
template <> struct is_proto_enum< ::apollo::localization::GnssPositionType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::GnssPositionType>() {
  return ::apollo::localization::GnssPositionType_descriptor();
}
template <> struct is_proto_enum< ::apollo::localization::ImuMsgDelayStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::ImuMsgDelayStatus>() {
  return ::apollo::localization::ImuMsgDelayStatus_descriptor();
}
template <> struct is_proto_enum< ::apollo::localization::ImuMsgMissingStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::ImuMsgMissingStatus>() {
  return ::apollo::localization::ImuMsgMissingStatus_descriptor();
}
template <> struct is_proto_enum< ::apollo::localization::ImuMsgDataStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::ImuMsgDataStatus>() {
  return ::apollo::localization::ImuMsgDataStatus_descriptor();
}
template <> struct is_proto_enum< ::apollo::localization::MsfRunningStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::MsfRunningStatus>() {
  return ::apollo::localization::MsfRunningStatus_descriptor();
}
template <> struct is_proto_enum< ::apollo::localization::MsfInitPoseSource> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::MsfInitPoseSource>() {
  return ::apollo::localization::MsfInitPoseSource_descriptor();
}
template <> struct is_proto_enum< ::apollo::localization::MsfGnssMapOffsetStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::MsfGnssMapOffsetStatus>() {
  return ::apollo::localization::MsfGnssMapOffsetStatus_descriptor();
}
template <> struct is_proto_enum< ::apollo::localization::MsfInitPoseStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::MsfInitPoseStatus>() {
  return ::apollo::localization::MsfInitPoseStatus_descriptor();
}
template <> struct is_proto_enum< ::apollo::localization::MSFInitStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::MSFInitStatus>() {
  return ::apollo::localization::MSFInitStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_modules_2fcommon_5fmsgs_2flocalization_5fmsgs_2flocalization_5fstatus_2eproto__INCLUDED
