// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/common_msgs/basic_msgs/vehicle_id.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "modules/common_msgs/basic_msgs/vehicle_id.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace apollo {
namespace common {
class VehicleIDDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<VehicleID>
     _instance;
} _VehicleID_default_instance_;

namespace protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fvehicle_5fid_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VehicleID, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VehicleID, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VehicleID, vin_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VehicleID, plate_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VehicleID, other_unique_id_),
  0,
  1,
  2,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(VehicleID)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_VehicleID_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "modules/common_msgs/basic_msgs/vehicle_id.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _VehicleID_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_VehicleID_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n/modules/common_msgs/basic_msgs/vehicle"
      "_id.proto\022\rapollo.common\"@\n\tVehicleID\022\013\n"
      "\003vin\030\001 \001(\t\022\r\n\005plate\030\002 \001(\t\022\027\n\017other_uniqu"
      "e_id\030\003 \001(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 130);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "modules/common_msgs/basic_msgs/vehicle_id.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fvehicle_5fid_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VehicleID::kVinFieldNumber;
const int VehicleID::kPlateFieldNumber;
const int VehicleID::kOtherUniqueIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VehicleID::VehicleID()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fvehicle_5fid_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.common.VehicleID)
}
VehicleID::VehicleID(const VehicleID& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  vin_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_vin()) {
    vin_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.vin_);
  }
  plate_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_plate()) {
    plate_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.plate_);
  }
  other_unique_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_other_unique_id()) {
    other_unique_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.other_unique_id_);
  }
  // @@protoc_insertion_point(copy_constructor:apollo.common.VehicleID)
}

void VehicleID::SharedCtor() {
  _cached_size_ = 0;
  vin_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  plate_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  other_unique_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

VehicleID::~VehicleID() {
  // @@protoc_insertion_point(destructor:apollo.common.VehicleID)
  SharedDtor();
}

void VehicleID::SharedDtor() {
  vin_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  plate_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  other_unique_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void VehicleID::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* VehicleID::descriptor() {
  protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fvehicle_5fid_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fvehicle_5fid_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const VehicleID& VehicleID::default_instance() {
  protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fvehicle_5fid_2eproto::InitDefaults();
  return *internal_default_instance();
}

VehicleID* VehicleID::New(::google::protobuf::Arena* arena) const {
  VehicleID* n = new VehicleID;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void VehicleID::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.common.VehicleID)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!vin_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*vin_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(!plate_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*plate_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(!other_unique_id_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*other_unique_id_.UnsafeRawStringPointer())->clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool VehicleID::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.common.VehicleID)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string vin = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_vin()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->vin().data(), static_cast<int>(this->vin().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.common.VehicleID.vin");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string plate = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_plate()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->plate().data(), static_cast<int>(this->plate().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.common.VehicleID.plate");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string other_unique_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_other_unique_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->other_unique_id().data(), static_cast<int>(this->other_unique_id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.common.VehicleID.other_unique_id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.common.VehicleID)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.common.VehicleID)
  return false;
#undef DO_
}

void VehicleID::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.common.VehicleID)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string vin = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->vin().data(), static_cast<int>(this->vin().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.common.VehicleID.vin");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->vin(), output);
  }

  // optional string plate = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->plate().data(), static_cast<int>(this->plate().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.common.VehicleID.plate");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->plate(), output);
  }

  // optional string other_unique_id = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->other_unique_id().data(), static_cast<int>(this->other_unique_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.common.VehicleID.other_unique_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->other_unique_id(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.common.VehicleID)
}

::google::protobuf::uint8* VehicleID::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.common.VehicleID)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string vin = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->vin().data(), static_cast<int>(this->vin().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.common.VehicleID.vin");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->vin(), target);
  }

  // optional string plate = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->plate().data(), static_cast<int>(this->plate().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.common.VehicleID.plate");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->plate(), target);
  }

  // optional string other_unique_id = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->other_unique_id().data(), static_cast<int>(this->other_unique_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.common.VehicleID.other_unique_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->other_unique_id(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.common.VehicleID)
  return target;
}

size_t VehicleID::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.common.VehicleID)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 7u) {
    // optional string vin = 1;
    if (has_vin()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->vin());
    }

    // optional string plate = 2;
    if (has_plate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->plate());
    }

    // optional string other_unique_id = 3;
    if (has_other_unique_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->other_unique_id());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void VehicleID::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.common.VehicleID)
  GOOGLE_DCHECK_NE(&from, this);
  const VehicleID* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const VehicleID>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.common.VehicleID)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.common.VehicleID)
    MergeFrom(*source);
  }
}

void VehicleID::MergeFrom(const VehicleID& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.common.VehicleID)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_vin();
      vin_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.vin_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_plate();
      plate_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.plate_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_other_unique_id();
      other_unique_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.other_unique_id_);
    }
  }
}

void VehicleID::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.common.VehicleID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VehicleID::CopyFrom(const VehicleID& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.common.VehicleID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VehicleID::IsInitialized() const {
  return true;
}

void VehicleID::Swap(VehicleID* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VehicleID::InternalSwap(VehicleID* other) {
  using std::swap;
  vin_.Swap(&other->vin_);
  plate_.Swap(&other->plate_);
  other_unique_id_.Swap(&other->other_unique_id_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata VehicleID::GetMetadata() const {
  protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fvehicle_5fid_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fvehicle_5fid_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// VehicleID

// optional string vin = 1;
bool VehicleID::has_vin() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void VehicleID::set_has_vin() {
  _has_bits_[0] |= 0x00000001u;
}
void VehicleID::clear_has_vin() {
  _has_bits_[0] &= ~0x00000001u;
}
void VehicleID::clear_vin() {
  vin_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_vin();
}
const ::std::string& VehicleID::vin() const {
  // @@protoc_insertion_point(field_get:apollo.common.VehicleID.vin)
  return vin_.GetNoArena();
}
void VehicleID::set_vin(const ::std::string& value) {
  set_has_vin();
  vin_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.common.VehicleID.vin)
}
#if LANG_CXX11
void VehicleID::set_vin(::std::string&& value) {
  set_has_vin();
  vin_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.common.VehicleID.vin)
}
#endif
void VehicleID::set_vin(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_vin();
  vin_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.common.VehicleID.vin)
}
void VehicleID::set_vin(const char* value, size_t size) {
  set_has_vin();
  vin_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.common.VehicleID.vin)
}
::std::string* VehicleID::mutable_vin() {
  set_has_vin();
  // @@protoc_insertion_point(field_mutable:apollo.common.VehicleID.vin)
  return vin_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* VehicleID::release_vin() {
  // @@protoc_insertion_point(field_release:apollo.common.VehicleID.vin)
  clear_has_vin();
  return vin_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void VehicleID::set_allocated_vin(::std::string* vin) {
  if (vin != NULL) {
    set_has_vin();
  } else {
    clear_has_vin();
  }
  vin_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), vin);
  // @@protoc_insertion_point(field_set_allocated:apollo.common.VehicleID.vin)
}

// optional string plate = 2;
bool VehicleID::has_plate() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void VehicleID::set_has_plate() {
  _has_bits_[0] |= 0x00000002u;
}
void VehicleID::clear_has_plate() {
  _has_bits_[0] &= ~0x00000002u;
}
void VehicleID::clear_plate() {
  plate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_plate();
}
const ::std::string& VehicleID::plate() const {
  // @@protoc_insertion_point(field_get:apollo.common.VehicleID.plate)
  return plate_.GetNoArena();
}
void VehicleID::set_plate(const ::std::string& value) {
  set_has_plate();
  plate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.common.VehicleID.plate)
}
#if LANG_CXX11
void VehicleID::set_plate(::std::string&& value) {
  set_has_plate();
  plate_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.common.VehicleID.plate)
}
#endif
void VehicleID::set_plate(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_plate();
  plate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.common.VehicleID.plate)
}
void VehicleID::set_plate(const char* value, size_t size) {
  set_has_plate();
  plate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.common.VehicleID.plate)
}
::std::string* VehicleID::mutable_plate() {
  set_has_plate();
  // @@protoc_insertion_point(field_mutable:apollo.common.VehicleID.plate)
  return plate_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* VehicleID::release_plate() {
  // @@protoc_insertion_point(field_release:apollo.common.VehicleID.plate)
  clear_has_plate();
  return plate_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void VehicleID::set_allocated_plate(::std::string* plate) {
  if (plate != NULL) {
    set_has_plate();
  } else {
    clear_has_plate();
  }
  plate_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), plate);
  // @@protoc_insertion_point(field_set_allocated:apollo.common.VehicleID.plate)
}

// optional string other_unique_id = 3;
bool VehicleID::has_other_unique_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void VehicleID::set_has_other_unique_id() {
  _has_bits_[0] |= 0x00000004u;
}
void VehicleID::clear_has_other_unique_id() {
  _has_bits_[0] &= ~0x00000004u;
}
void VehicleID::clear_other_unique_id() {
  other_unique_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_other_unique_id();
}
const ::std::string& VehicleID::other_unique_id() const {
  // @@protoc_insertion_point(field_get:apollo.common.VehicleID.other_unique_id)
  return other_unique_id_.GetNoArena();
}
void VehicleID::set_other_unique_id(const ::std::string& value) {
  set_has_other_unique_id();
  other_unique_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.common.VehicleID.other_unique_id)
}
#if LANG_CXX11
void VehicleID::set_other_unique_id(::std::string&& value) {
  set_has_other_unique_id();
  other_unique_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.common.VehicleID.other_unique_id)
}
#endif
void VehicleID::set_other_unique_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_other_unique_id();
  other_unique_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.common.VehicleID.other_unique_id)
}
void VehicleID::set_other_unique_id(const char* value, size_t size) {
  set_has_other_unique_id();
  other_unique_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.common.VehicleID.other_unique_id)
}
::std::string* VehicleID::mutable_other_unique_id() {
  set_has_other_unique_id();
  // @@protoc_insertion_point(field_mutable:apollo.common.VehicleID.other_unique_id)
  return other_unique_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* VehicleID::release_other_unique_id() {
  // @@protoc_insertion_point(field_release:apollo.common.VehicleID.other_unique_id)
  clear_has_other_unique_id();
  return other_unique_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void VehicleID::set_allocated_other_unique_id(::std::string* other_unique_id) {
  if (other_unique_id != NULL) {
    set_has_other_unique_id();
  } else {
    clear_has_other_unique_id();
  }
  other_unique_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), other_unique_id);
  // @@protoc_insertion_point(field_set_allocated:apollo.common.VehicleID.other_unique_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace apollo

// @@protoc_insertion_point(global_scope)
