// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/common_msgs/map_msgs/map_rsu.proto

#ifndef PROTOBUF_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5frsu_2eproto__INCLUDED
#define PROTOBUF_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5frsu_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "modules/common_msgs/map_msgs/map_id.pb.h"
// @@protoc_insertion_point(includes)
namespace apollo {
namespace hdmap {
class RSU;
class RSUDefaultTypeInternal;
extern RSUDefaultTypeInternal _RSU_default_instance_;
}  // namespace hdmap
}  // namespace apollo

namespace apollo {
namespace hdmap {

namespace protobuf_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5frsu_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5frsu_2eproto

// ===================================================================

class RSU : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.hdmap.RSU) */ {
 public:
  RSU();
  virtual ~RSU();

  RSU(const RSU& from);

  inline RSU& operator=(const RSU& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RSU(RSU&& from) noexcept
    : RSU() {
    *this = ::std::move(from);
  }

  inline RSU& operator=(RSU&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RSU& default_instance();

  static inline const RSU* internal_default_instance() {
    return reinterpret_cast<const RSU*>(
               &_RSU_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RSU* other);
  friend void swap(RSU& a, RSU& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RSU* New() const PROTOBUF_FINAL { return New(NULL); }

  RSU* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RSU& from);
  void MergeFrom(const RSU& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RSU* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.hdmap.Id overlap_id = 3;
  int overlap_id_size() const;
  void clear_overlap_id();
  static const int kOverlapIdFieldNumber = 3;
  const ::apollo::hdmap::Id& overlap_id(int index) const;
  ::apollo::hdmap::Id* mutable_overlap_id(int index);
  ::apollo::hdmap::Id* add_overlap_id();
  ::google::protobuf::RepeatedPtrField< ::apollo::hdmap::Id >*
      mutable_overlap_id();
  const ::google::protobuf::RepeatedPtrField< ::apollo::hdmap::Id >&
      overlap_id() const;

  // optional .apollo.hdmap.Id id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::apollo::hdmap::Id& id() const;
  ::apollo::hdmap::Id* mutable_id();
  ::apollo::hdmap::Id* release_id();
  void set_allocated_id(::apollo::hdmap::Id* id);

  // optional .apollo.hdmap.Id junction_id = 2;
  bool has_junction_id() const;
  void clear_junction_id();
  static const int kJunctionIdFieldNumber = 2;
  const ::apollo::hdmap::Id& junction_id() const;
  ::apollo::hdmap::Id* mutable_junction_id();
  ::apollo::hdmap::Id* release_junction_id();
  void set_allocated_junction_id(::apollo::hdmap::Id* junction_id);

  // @@protoc_insertion_point(class_scope:apollo.hdmap.RSU)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_junction_id();
  void clear_has_junction_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::hdmap::Id > overlap_id_;
  ::apollo::hdmap::Id* id_;
  ::apollo::hdmap::Id* junction_id_;
  friend struct protobuf_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5frsu_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RSU

// optional .apollo.hdmap.Id id = 1;
inline bool RSU::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RSU::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RSU::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RSU::clear_id() {
  if (id_ != NULL) id_->::apollo::hdmap::Id::Clear();
  clear_has_id();
}
inline const ::apollo::hdmap::Id& RSU::id() const {
  const ::apollo::hdmap::Id* p = id_;
  // @@protoc_insertion_point(field_get:apollo.hdmap.RSU.id)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::hdmap::Id*>(
      &::apollo::hdmap::_Id_default_instance_);
}
inline ::apollo::hdmap::Id* RSU::mutable_id() {
  set_has_id();
  if (id_ == NULL) {
    id_ = new ::apollo::hdmap::Id;
  }
  // @@protoc_insertion_point(field_mutable:apollo.hdmap.RSU.id)
  return id_;
}
inline ::apollo::hdmap::Id* RSU::release_id() {
  // @@protoc_insertion_point(field_release:apollo.hdmap.RSU.id)
  clear_has_id();
  ::apollo::hdmap::Id* temp = id_;
  id_ = NULL;
  return temp;
}
inline void RSU::set_allocated_id(::apollo::hdmap::Id* id) {
  delete id_;
  id_ = id;
  if (id) {
    set_has_id();
  } else {
    clear_has_id();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.hdmap.RSU.id)
}

// optional .apollo.hdmap.Id junction_id = 2;
inline bool RSU::has_junction_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RSU::set_has_junction_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RSU::clear_has_junction_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RSU::clear_junction_id() {
  if (junction_id_ != NULL) junction_id_->::apollo::hdmap::Id::Clear();
  clear_has_junction_id();
}
inline const ::apollo::hdmap::Id& RSU::junction_id() const {
  const ::apollo::hdmap::Id* p = junction_id_;
  // @@protoc_insertion_point(field_get:apollo.hdmap.RSU.junction_id)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::hdmap::Id*>(
      &::apollo::hdmap::_Id_default_instance_);
}
inline ::apollo::hdmap::Id* RSU::mutable_junction_id() {
  set_has_junction_id();
  if (junction_id_ == NULL) {
    junction_id_ = new ::apollo::hdmap::Id;
  }
  // @@protoc_insertion_point(field_mutable:apollo.hdmap.RSU.junction_id)
  return junction_id_;
}
inline ::apollo::hdmap::Id* RSU::release_junction_id() {
  // @@protoc_insertion_point(field_release:apollo.hdmap.RSU.junction_id)
  clear_has_junction_id();
  ::apollo::hdmap::Id* temp = junction_id_;
  junction_id_ = NULL;
  return temp;
}
inline void RSU::set_allocated_junction_id(::apollo::hdmap::Id* junction_id) {
  delete junction_id_;
  junction_id_ = junction_id;
  if (junction_id) {
    set_has_junction_id();
  } else {
    clear_has_junction_id();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.hdmap.RSU.junction_id)
}

// repeated .apollo.hdmap.Id overlap_id = 3;
inline int RSU::overlap_id_size() const {
  return overlap_id_.size();
}
inline void RSU::clear_overlap_id() {
  overlap_id_.Clear();
}
inline const ::apollo::hdmap::Id& RSU::overlap_id(int index) const {
  // @@protoc_insertion_point(field_get:apollo.hdmap.RSU.overlap_id)
  return overlap_id_.Get(index);
}
inline ::apollo::hdmap::Id* RSU::mutable_overlap_id(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.hdmap.RSU.overlap_id)
  return overlap_id_.Mutable(index);
}
inline ::apollo::hdmap::Id* RSU::add_overlap_id() {
  // @@protoc_insertion_point(field_add:apollo.hdmap.RSU.overlap_id)
  return overlap_id_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::hdmap::Id >*
RSU::mutable_overlap_id() {
  // @@protoc_insertion_point(field_mutable_list:apollo.hdmap.RSU.overlap_id)
  return &overlap_id_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::hdmap::Id >&
RSU::overlap_id() const {
  // @@protoc_insertion_point(field_list:apollo.hdmap.RSU.overlap_id)
  return overlap_id_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace hdmap
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5frsu_2eproto__INCLUDED
