// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/common_msgs/routing_msgs/geometry.proto

#ifndef PROTOBUF_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto__INCLUDED
#define PROTOBUF_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "modules/common_msgs/basic_msgs/geometry.pb.h"
// @@protoc_insertion_point(includes)
namespace apollo {
namespace routing {
class LaneSegment;
class LaneSegmentDefaultTypeInternal;
extern LaneSegmentDefaultTypeInternal _LaneSegment_default_instance_;
class LaneWaypoint;
class LaneWaypointDefaultTypeInternal;
extern LaneWaypointDefaultTypeInternal _LaneWaypoint_default_instance_;
class Measurement;
class MeasurementDefaultTypeInternal;
extern MeasurementDefaultTypeInternal _Measurement_default_instance_;
class Passage;
class PassageDefaultTypeInternal;
extern PassageDefaultTypeInternal _Passage_default_instance_;
class RoadSegment;
class RoadSegmentDefaultTypeInternal;
extern RoadSegmentDefaultTypeInternal _RoadSegment_default_instance_;
}  // namespace routing
}  // namespace apollo

namespace apollo {
namespace routing {

namespace protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto

enum DeadEndRoutingType {
  ROUTING_OTHER = 0,
  ROUTING_IN = 1,
  ROUTING_OUT = 2
};
bool DeadEndRoutingType_IsValid(int value);
const DeadEndRoutingType DeadEndRoutingType_MIN = ROUTING_OTHER;
const DeadEndRoutingType DeadEndRoutingType_MAX = ROUTING_OUT;
const int DeadEndRoutingType_ARRAYSIZE = DeadEndRoutingType_MAX + 1;

const ::google::protobuf::EnumDescriptor* DeadEndRoutingType_descriptor();
inline const ::std::string& DeadEndRoutingType_Name(DeadEndRoutingType value) {
  return ::google::protobuf::internal::NameOfEnum(
    DeadEndRoutingType_descriptor(), value);
}
inline bool DeadEndRoutingType_Parse(
    const ::std::string& name, DeadEndRoutingType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DeadEndRoutingType>(
    DeadEndRoutingType_descriptor(), name, value);
}
enum ChangeLaneType {
  FORWARD = 0,
  LEFT = 1,
  RIGHT = 2
};
bool ChangeLaneType_IsValid(int value);
const ChangeLaneType ChangeLaneType_MIN = FORWARD;
const ChangeLaneType ChangeLaneType_MAX = RIGHT;
const int ChangeLaneType_ARRAYSIZE = ChangeLaneType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ChangeLaneType_descriptor();
inline const ::std::string& ChangeLaneType_Name(ChangeLaneType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ChangeLaneType_descriptor(), value);
}
inline bool ChangeLaneType_Parse(
    const ::std::string& name, ChangeLaneType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ChangeLaneType>(
    ChangeLaneType_descriptor(), name, value);
}
// ===================================================================

class LaneWaypoint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.LaneWaypoint) */ {
 public:
  LaneWaypoint();
  virtual ~LaneWaypoint();

  LaneWaypoint(const LaneWaypoint& from);

  inline LaneWaypoint& operator=(const LaneWaypoint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LaneWaypoint(LaneWaypoint&& from) noexcept
    : LaneWaypoint() {
    *this = ::std::move(from);
  }

  inline LaneWaypoint& operator=(LaneWaypoint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LaneWaypoint& default_instance();

  static inline const LaneWaypoint* internal_default_instance() {
    return reinterpret_cast<const LaneWaypoint*>(
               &_LaneWaypoint_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(LaneWaypoint* other);
  friend void swap(LaneWaypoint& a, LaneWaypoint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LaneWaypoint* New() const PROTOBUF_FINAL { return New(NULL); }

  LaneWaypoint* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LaneWaypoint& from);
  void MergeFrom(const LaneWaypoint& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LaneWaypoint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional .apollo.common.PointENU pose = 3;
  bool has_pose() const;
  void clear_pose();
  static const int kPoseFieldNumber = 3;
  const ::apollo::common::PointENU& pose() const;
  ::apollo::common::PointENU* mutable_pose();
  ::apollo::common::PointENU* release_pose();
  void set_allocated_pose(::apollo::common::PointENU* pose);

  // optional double s = 2;
  bool has_s() const;
  void clear_s();
  static const int kSFieldNumber = 2;
  double s() const;
  void set_s(double value);

  // optional double heading = 4;
  bool has_heading() const;
  void clear_heading();
  static const int kHeadingFieldNumber = 4;
  double heading() const;
  void set_heading(double value);

  // @@protoc_insertion_point(class_scope:apollo.routing.LaneWaypoint)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_s();
  void clear_has_s();
  void set_has_pose();
  void clear_has_pose();
  void set_has_heading();
  void clear_has_heading();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::apollo::common::PointENU* pose_;
  double s_;
  double heading_;
  friend struct protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LaneSegment : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.LaneSegment) */ {
 public:
  LaneSegment();
  virtual ~LaneSegment();

  LaneSegment(const LaneSegment& from);

  inline LaneSegment& operator=(const LaneSegment& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LaneSegment(LaneSegment&& from) noexcept
    : LaneSegment() {
    *this = ::std::move(from);
  }

  inline LaneSegment& operator=(LaneSegment&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LaneSegment& default_instance();

  static inline const LaneSegment* internal_default_instance() {
    return reinterpret_cast<const LaneSegment*>(
               &_LaneSegment_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(LaneSegment* other);
  friend void swap(LaneSegment& a, LaneSegment& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LaneSegment* New() const PROTOBUF_FINAL { return New(NULL); }

  LaneSegment* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LaneSegment& from);
  void MergeFrom(const LaneSegment& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LaneSegment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional double start_s = 2;
  bool has_start_s() const;
  void clear_start_s();
  static const int kStartSFieldNumber = 2;
  double start_s() const;
  void set_start_s(double value);

  // optional double end_s = 3;
  bool has_end_s() const;
  void clear_end_s();
  static const int kEndSFieldNumber = 3;
  double end_s() const;
  void set_end_s(double value);

  // @@protoc_insertion_point(class_scope:apollo.routing.LaneSegment)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_start_s();
  void clear_has_start_s();
  void set_has_end_s();
  void clear_has_end_s();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  double start_s_;
  double end_s_;
  friend struct protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Measurement : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.Measurement) */ {
 public:
  Measurement();
  virtual ~Measurement();

  Measurement(const Measurement& from);

  inline Measurement& operator=(const Measurement& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Measurement(Measurement&& from) noexcept
    : Measurement() {
    *this = ::std::move(from);
  }

  inline Measurement& operator=(Measurement&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Measurement& default_instance();

  static inline const Measurement* internal_default_instance() {
    return reinterpret_cast<const Measurement*>(
               &_Measurement_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Measurement* other);
  friend void swap(Measurement& a, Measurement& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Measurement* New() const PROTOBUF_FINAL { return New(NULL); }

  Measurement* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Measurement& from);
  void MergeFrom(const Measurement& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Measurement* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double distance = 1;
  bool has_distance() const;
  void clear_distance();
  static const int kDistanceFieldNumber = 1;
  double distance() const;
  void set_distance(double value);

  // @@protoc_insertion_point(class_scope:apollo.routing.Measurement)
 private:
  void set_has_distance();
  void clear_has_distance();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double distance_;
  friend struct protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Passage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.Passage) */ {
 public:
  Passage();
  virtual ~Passage();

  Passage(const Passage& from);

  inline Passage& operator=(const Passage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Passage(Passage&& from) noexcept
    : Passage() {
    *this = ::std::move(from);
  }

  inline Passage& operator=(Passage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Passage& default_instance();

  static inline const Passage* internal_default_instance() {
    return reinterpret_cast<const Passage*>(
               &_Passage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Passage* other);
  friend void swap(Passage& a, Passage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Passage* New() const PROTOBUF_FINAL { return New(NULL); }

  Passage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Passage& from);
  void MergeFrom(const Passage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Passage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.routing.LaneSegment segment = 1;
  int segment_size() const;
  void clear_segment();
  static const int kSegmentFieldNumber = 1;
  const ::apollo::routing::LaneSegment& segment(int index) const;
  ::apollo::routing::LaneSegment* mutable_segment(int index);
  ::apollo::routing::LaneSegment* add_segment();
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >*
      mutable_segment();
  const ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >&
      segment() const;

  // optional bool can_exit = 2;
  bool has_can_exit() const;
  void clear_can_exit();
  static const int kCanExitFieldNumber = 2;
  bool can_exit() const;
  void set_can_exit(bool value);

  // optional .apollo.routing.ChangeLaneType change_lane_type = 3 [default = FORWARD];
  bool has_change_lane_type() const;
  void clear_change_lane_type();
  static const int kChangeLaneTypeFieldNumber = 3;
  ::apollo::routing::ChangeLaneType change_lane_type() const;
  void set_change_lane_type(::apollo::routing::ChangeLaneType value);

  // @@protoc_insertion_point(class_scope:apollo.routing.Passage)
 private:
  void set_has_can_exit();
  void clear_has_can_exit();
  void set_has_change_lane_type();
  void clear_has_change_lane_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment > segment_;
  bool can_exit_;
  int change_lane_type_;
  friend struct protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RoadSegment : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.RoadSegment) */ {
 public:
  RoadSegment();
  virtual ~RoadSegment();

  RoadSegment(const RoadSegment& from);

  inline RoadSegment& operator=(const RoadSegment& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoadSegment(RoadSegment&& from) noexcept
    : RoadSegment() {
    *this = ::std::move(from);
  }

  inline RoadSegment& operator=(RoadSegment&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoadSegment& default_instance();

  static inline const RoadSegment* internal_default_instance() {
    return reinterpret_cast<const RoadSegment*>(
               &_RoadSegment_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(RoadSegment* other);
  friend void swap(RoadSegment& a, RoadSegment& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoadSegment* New() const PROTOBUF_FINAL { return New(NULL); }

  RoadSegment* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RoadSegment& from);
  void MergeFrom(const RoadSegment& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RoadSegment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.routing.Passage passage = 2;
  int passage_size() const;
  void clear_passage();
  static const int kPassageFieldNumber = 2;
  const ::apollo::routing::Passage& passage(int index) const;
  ::apollo::routing::Passage* mutable_passage(int index);
  ::apollo::routing::Passage* add_passage();
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::Passage >*
      mutable_passage();
  const ::google::protobuf::RepeatedPtrField< ::apollo::routing::Passage >&
      passage() const;

  // optional string id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // @@protoc_insertion_point(class_scope:apollo.routing.RoadSegment)
 private:
  void set_has_id();
  void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::Passage > passage_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  friend struct protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LaneWaypoint

// optional string id = 1;
inline bool LaneWaypoint::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LaneWaypoint::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LaneWaypoint::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LaneWaypoint::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& LaneWaypoint::id() const {
  // @@protoc_insertion_point(field_get:apollo.routing.LaneWaypoint.id)
  return id_.GetNoArena();
}
inline void LaneWaypoint::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.routing.LaneWaypoint.id)
}
#if LANG_CXX11
inline void LaneWaypoint::set_id(::std::string&& value) {
  set_has_id();
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.routing.LaneWaypoint.id)
}
#endif
inline void LaneWaypoint::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.routing.LaneWaypoint.id)
}
inline void LaneWaypoint::set_id(const char* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.LaneWaypoint.id)
}
inline ::std::string* LaneWaypoint::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:apollo.routing.LaneWaypoint.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LaneWaypoint::release_id() {
  // @@protoc_insertion_point(field_release:apollo.routing.LaneWaypoint.id)
  clear_has_id();
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LaneWaypoint::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.LaneWaypoint.id)
}

// optional double s = 2;
inline bool LaneWaypoint::has_s() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LaneWaypoint::set_has_s() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LaneWaypoint::clear_has_s() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LaneWaypoint::clear_s() {
  s_ = 0;
  clear_has_s();
}
inline double LaneWaypoint::s() const {
  // @@protoc_insertion_point(field_get:apollo.routing.LaneWaypoint.s)
  return s_;
}
inline void LaneWaypoint::set_s(double value) {
  set_has_s();
  s_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.LaneWaypoint.s)
}

// optional .apollo.common.PointENU pose = 3;
inline bool LaneWaypoint::has_pose() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LaneWaypoint::set_has_pose() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LaneWaypoint::clear_has_pose() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LaneWaypoint::clear_pose() {
  if (pose_ != NULL) pose_->::apollo::common::PointENU::Clear();
  clear_has_pose();
}
inline const ::apollo::common::PointENU& LaneWaypoint::pose() const {
  const ::apollo::common::PointENU* p = pose_;
  // @@protoc_insertion_point(field_get:apollo.routing.LaneWaypoint.pose)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::common::PointENU*>(
      &::apollo::common::_PointENU_default_instance_);
}
inline ::apollo::common::PointENU* LaneWaypoint::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) {
    pose_ = new ::apollo::common::PointENU;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.LaneWaypoint.pose)
  return pose_;
}
inline ::apollo::common::PointENU* LaneWaypoint::release_pose() {
  // @@protoc_insertion_point(field_release:apollo.routing.LaneWaypoint.pose)
  clear_has_pose();
  ::apollo::common::PointENU* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void LaneWaypoint::set_allocated_pose(::apollo::common::PointENU* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.LaneWaypoint.pose)
}

// optional double heading = 4;
inline bool LaneWaypoint::has_heading() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LaneWaypoint::set_has_heading() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LaneWaypoint::clear_has_heading() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LaneWaypoint::clear_heading() {
  heading_ = 0;
  clear_has_heading();
}
inline double LaneWaypoint::heading() const {
  // @@protoc_insertion_point(field_get:apollo.routing.LaneWaypoint.heading)
  return heading_;
}
inline void LaneWaypoint::set_heading(double value) {
  set_has_heading();
  heading_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.LaneWaypoint.heading)
}

// -------------------------------------------------------------------

// LaneSegment

// optional string id = 1;
inline bool LaneSegment::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LaneSegment::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LaneSegment::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LaneSegment::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& LaneSegment::id() const {
  // @@protoc_insertion_point(field_get:apollo.routing.LaneSegment.id)
  return id_.GetNoArena();
}
inline void LaneSegment::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.routing.LaneSegment.id)
}
#if LANG_CXX11
inline void LaneSegment::set_id(::std::string&& value) {
  set_has_id();
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.routing.LaneSegment.id)
}
#endif
inline void LaneSegment::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.routing.LaneSegment.id)
}
inline void LaneSegment::set_id(const char* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.LaneSegment.id)
}
inline ::std::string* LaneSegment::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:apollo.routing.LaneSegment.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LaneSegment::release_id() {
  // @@protoc_insertion_point(field_release:apollo.routing.LaneSegment.id)
  clear_has_id();
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LaneSegment::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.LaneSegment.id)
}

// optional double start_s = 2;
inline bool LaneSegment::has_start_s() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LaneSegment::set_has_start_s() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LaneSegment::clear_has_start_s() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LaneSegment::clear_start_s() {
  start_s_ = 0;
  clear_has_start_s();
}
inline double LaneSegment::start_s() const {
  // @@protoc_insertion_point(field_get:apollo.routing.LaneSegment.start_s)
  return start_s_;
}
inline void LaneSegment::set_start_s(double value) {
  set_has_start_s();
  start_s_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.LaneSegment.start_s)
}

// optional double end_s = 3;
inline bool LaneSegment::has_end_s() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LaneSegment::set_has_end_s() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LaneSegment::clear_has_end_s() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LaneSegment::clear_end_s() {
  end_s_ = 0;
  clear_has_end_s();
}
inline double LaneSegment::end_s() const {
  // @@protoc_insertion_point(field_get:apollo.routing.LaneSegment.end_s)
  return end_s_;
}
inline void LaneSegment::set_end_s(double value) {
  set_has_end_s();
  end_s_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.LaneSegment.end_s)
}

// -------------------------------------------------------------------

// Measurement

// optional double distance = 1;
inline bool Measurement::has_distance() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Measurement::set_has_distance() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Measurement::clear_has_distance() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Measurement::clear_distance() {
  distance_ = 0;
  clear_has_distance();
}
inline double Measurement::distance() const {
  // @@protoc_insertion_point(field_get:apollo.routing.Measurement.distance)
  return distance_;
}
inline void Measurement::set_distance(double value) {
  set_has_distance();
  distance_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.Measurement.distance)
}

// -------------------------------------------------------------------

// Passage

// repeated .apollo.routing.LaneSegment segment = 1;
inline int Passage::segment_size() const {
  return segment_.size();
}
inline void Passage::clear_segment() {
  segment_.Clear();
}
inline const ::apollo::routing::LaneSegment& Passage::segment(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.Passage.segment)
  return segment_.Get(index);
}
inline ::apollo::routing::LaneSegment* Passage::mutable_segment(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.Passage.segment)
  return segment_.Mutable(index);
}
inline ::apollo::routing::LaneSegment* Passage::add_segment() {
  // @@protoc_insertion_point(field_add:apollo.routing.Passage.segment)
  return segment_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >*
Passage::mutable_segment() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.Passage.segment)
  return &segment_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >&
Passage::segment() const {
  // @@protoc_insertion_point(field_list:apollo.routing.Passage.segment)
  return segment_;
}

// optional bool can_exit = 2;
inline bool Passage::has_can_exit() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Passage::set_has_can_exit() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Passage::clear_has_can_exit() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Passage::clear_can_exit() {
  can_exit_ = false;
  clear_has_can_exit();
}
inline bool Passage::can_exit() const {
  // @@protoc_insertion_point(field_get:apollo.routing.Passage.can_exit)
  return can_exit_;
}
inline void Passage::set_can_exit(bool value) {
  set_has_can_exit();
  can_exit_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.Passage.can_exit)
}

// optional .apollo.routing.ChangeLaneType change_lane_type = 3 [default = FORWARD];
inline bool Passage::has_change_lane_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Passage::set_has_change_lane_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Passage::clear_has_change_lane_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Passage::clear_change_lane_type() {
  change_lane_type_ = 0;
  clear_has_change_lane_type();
}
inline ::apollo::routing::ChangeLaneType Passage::change_lane_type() const {
  // @@protoc_insertion_point(field_get:apollo.routing.Passage.change_lane_type)
  return static_cast< ::apollo::routing::ChangeLaneType >(change_lane_type_);
}
inline void Passage::set_change_lane_type(::apollo::routing::ChangeLaneType value) {
  assert(::apollo::routing::ChangeLaneType_IsValid(value));
  set_has_change_lane_type();
  change_lane_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.Passage.change_lane_type)
}

// -------------------------------------------------------------------

// RoadSegment

// optional string id = 1;
inline bool RoadSegment::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RoadSegment::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RoadSegment::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RoadSegment::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& RoadSegment::id() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoadSegment.id)
  return id_.GetNoArena();
}
inline void RoadSegment::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.routing.RoadSegment.id)
}
#if LANG_CXX11
inline void RoadSegment::set_id(::std::string&& value) {
  set_has_id();
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.routing.RoadSegment.id)
}
#endif
inline void RoadSegment::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.routing.RoadSegment.id)
}
inline void RoadSegment::set_id(const char* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.RoadSegment.id)
}
inline ::std::string* RoadSegment::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoadSegment.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoadSegment::release_id() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoadSegment.id)
  clear_has_id();
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoadSegment::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoadSegment.id)
}

// repeated .apollo.routing.Passage passage = 2;
inline int RoadSegment::passage_size() const {
  return passage_.size();
}
inline void RoadSegment::clear_passage() {
  passage_.Clear();
}
inline const ::apollo::routing::Passage& RoadSegment::passage(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoadSegment.passage)
  return passage_.Get(index);
}
inline ::apollo::routing::Passage* RoadSegment::mutable_passage(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoadSegment.passage)
  return passage_.Mutable(index);
}
inline ::apollo::routing::Passage* RoadSegment::add_passage() {
  // @@protoc_insertion_point(field_add:apollo.routing.RoadSegment.passage)
  return passage_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::routing::Passage >*
RoadSegment::mutable_passage() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.RoadSegment.passage)
  return &passage_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::routing::Passage >&
RoadSegment::passage() const {
  // @@protoc_insertion_point(field_list:apollo.routing.RoadSegment.passage)
  return passage_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace routing
}  // namespace apollo

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::routing::DeadEndRoutingType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::routing::DeadEndRoutingType>() {
  return ::apollo::routing::DeadEndRoutingType_descriptor();
}
template <> struct is_proto_enum< ::apollo::routing::ChangeLaneType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::routing::ChangeLaneType>() {
  return ::apollo::routing::ChangeLaneType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto__INCLUDED
