// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/common_msgs/routing_msgs/routing.proto

#ifndef PROTOBUF_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto__INCLUDED
#define PROTOBUF_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "modules/common_msgs/routing_msgs/geometry.pb.h"
#include "modules/common_msgs/basic_msgs/header.pb.h"
#include "modules/common_msgs/basic_msgs/error_code.pb.h"
#include "modules/common_msgs/routing_msgs/poi.pb.h"
// @@protoc_insertion_point(includes)
namespace apollo {
namespace routing {
class RoutingRequest;
class RoutingRequestDefaultTypeInternal;
extern RoutingRequestDefaultTypeInternal _RoutingRequest_default_instance_;
class RoutingResponse;
class RoutingResponseDefaultTypeInternal;
extern RoutingResponseDefaultTypeInternal _RoutingResponse_default_instance_;
}  // namespace routing
}  // namespace apollo

namespace apollo {
namespace routing {

namespace protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto

// ===================================================================

class RoutingRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.RoutingRequest) */ {
 public:
  RoutingRequest();
  virtual ~RoutingRequest();

  RoutingRequest(const RoutingRequest& from);

  inline RoutingRequest& operator=(const RoutingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoutingRequest(RoutingRequest&& from) noexcept
    : RoutingRequest() {
    *this = ::std::move(from);
  }

  inline RoutingRequest& operator=(RoutingRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoutingRequest& default_instance();

  static inline const RoutingRequest* internal_default_instance() {
    return reinterpret_cast<const RoutingRequest*>(
               &_RoutingRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RoutingRequest* other);
  friend void swap(RoutingRequest& a, RoutingRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoutingRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  RoutingRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RoutingRequest& from);
  void MergeFrom(const RoutingRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RoutingRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.routing.LaneWaypoint waypoint = 2;
  int waypoint_size() const;
  void clear_waypoint();
  static const int kWaypointFieldNumber = 2;
  const ::apollo::routing::LaneWaypoint& waypoint(int index) const;
  ::apollo::routing::LaneWaypoint* mutable_waypoint(int index);
  ::apollo::routing::LaneWaypoint* add_waypoint();
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneWaypoint >*
      mutable_waypoint();
  const ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneWaypoint >&
      waypoint() const;

  // repeated .apollo.routing.LaneSegment blacklisted_lane = 3;
  int blacklisted_lane_size() const;
  void clear_blacklisted_lane();
  static const int kBlacklistedLaneFieldNumber = 3;
  const ::apollo::routing::LaneSegment& blacklisted_lane(int index) const;
  ::apollo::routing::LaneSegment* mutable_blacklisted_lane(int index);
  ::apollo::routing::LaneSegment* add_blacklisted_lane();
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >*
      mutable_blacklisted_lane();
  const ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >&
      blacklisted_lane() const;

  // repeated string blacklisted_road = 4;
  int blacklisted_road_size() const;
  void clear_blacklisted_road();
  static const int kBlacklistedRoadFieldNumber = 4;
  const ::std::string& blacklisted_road(int index) const;
  ::std::string* mutable_blacklisted_road(int index);
  void set_blacklisted_road(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_blacklisted_road(int index, ::std::string&& value);
  #endif
  void set_blacklisted_road(int index, const char* value);
  void set_blacklisted_road(int index, const char* value, size_t size);
  ::std::string* add_blacklisted_road();
  void add_blacklisted_road(const ::std::string& value);
  #if LANG_CXX11
  void add_blacklisted_road(::std::string&& value);
  #endif
  void add_blacklisted_road(const char* value);
  void add_blacklisted_road(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& blacklisted_road() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_blacklisted_road();

  // optional .apollo.common.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* mutable_header();
  ::apollo::common::Header* release_header();
  void set_allocated_header(::apollo::common::Header* header);

  // optional .apollo.routing.ParkingInfo parking_info = 6 [deprecated = true];
  GOOGLE_PROTOBUF_DEPRECATED_ATTR bool has_parking_info() const;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR void clear_parking_info();
  GOOGLE_PROTOBUF_DEPRECATED_ATTR static const int kParkingInfoFieldNumber = 6;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR const ::apollo::routing::ParkingInfo& parking_info() const;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR ::apollo::routing::ParkingInfo* mutable_parking_info();
  GOOGLE_PROTOBUF_DEPRECATED_ATTR ::apollo::routing::ParkingInfo* release_parking_info();
  GOOGLE_PROTOBUF_DEPRECATED_ATTR void set_allocated_parking_info(::apollo::routing::ParkingInfo* parking_info);

  // optional bool is_start_pose_set = 7 [default = false];
  bool has_is_start_pose_set() const;
  void clear_is_start_pose_set();
  static const int kIsStartPoseSetFieldNumber = 7;
  bool is_start_pose_set() const;
  void set_is_start_pose_set(bool value);

  // optional bool broadcast = 5 [default = true];
  bool has_broadcast() const;
  void clear_broadcast();
  static const int kBroadcastFieldNumber = 5;
  bool broadcast() const;
  void set_broadcast(bool value);

  // @@protoc_insertion_point(class_scope:apollo.routing.RoutingRequest)
 private:
  void set_has_header();
  void clear_has_header();
  void set_has_broadcast();
  void clear_has_broadcast();
  void set_has_parking_info();
  void clear_has_parking_info();
  void set_has_is_start_pose_set();
  void clear_has_is_start_pose_set();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneWaypoint > waypoint_;
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment > blacklisted_lane_;
  ::google::protobuf::RepeatedPtrField< ::std::string> blacklisted_road_;
  ::apollo::common::Header* header_;
  ::apollo::routing::ParkingInfo* parking_info_;
  bool is_start_pose_set_;
  bool broadcast_;
  friend struct protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RoutingResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.RoutingResponse) */ {
 public:
  RoutingResponse();
  virtual ~RoutingResponse();

  RoutingResponse(const RoutingResponse& from);

  inline RoutingResponse& operator=(const RoutingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoutingResponse(RoutingResponse&& from) noexcept
    : RoutingResponse() {
    *this = ::std::move(from);
  }

  inline RoutingResponse& operator=(RoutingResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoutingResponse& default_instance();

  static inline const RoutingResponse* internal_default_instance() {
    return reinterpret_cast<const RoutingResponse*>(
               &_RoutingResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(RoutingResponse* other);
  friend void swap(RoutingResponse& a, RoutingResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoutingResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  RoutingResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RoutingResponse& from);
  void MergeFrom(const RoutingResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RoutingResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.routing.RoadSegment road = 2;
  int road_size() const;
  void clear_road();
  static const int kRoadFieldNumber = 2;
  const ::apollo::routing::RoadSegment& road(int index) const;
  ::apollo::routing::RoadSegment* mutable_road(int index);
  ::apollo::routing::RoadSegment* add_road();
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::RoadSegment >*
      mutable_road();
  const ::google::protobuf::RepeatedPtrField< ::apollo::routing::RoadSegment >&
      road() const;

  // optional bytes map_version = 5;
  bool has_map_version() const;
  void clear_map_version();
  static const int kMapVersionFieldNumber = 5;
  const ::std::string& map_version() const;
  void set_map_version(const ::std::string& value);
  #if LANG_CXX11
  void set_map_version(::std::string&& value);
  #endif
  void set_map_version(const char* value);
  void set_map_version(const void* value, size_t size);
  ::std::string* mutable_map_version();
  ::std::string* release_map_version();
  void set_allocated_map_version(::std::string* map_version);

  // optional .apollo.common.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* mutable_header();
  ::apollo::common::Header* release_header();
  void set_allocated_header(::apollo::common::Header* header);

  // optional .apollo.routing.Measurement measurement = 3;
  bool has_measurement() const;
  void clear_measurement();
  static const int kMeasurementFieldNumber = 3;
  const ::apollo::routing::Measurement& measurement() const;
  ::apollo::routing::Measurement* mutable_measurement();
  ::apollo::routing::Measurement* release_measurement();
  void set_allocated_measurement(::apollo::routing::Measurement* measurement);

  // optional .apollo.routing.RoutingRequest routing_request = 4;
  bool has_routing_request() const;
  void clear_routing_request();
  static const int kRoutingRequestFieldNumber = 4;
  const ::apollo::routing::RoutingRequest& routing_request() const;
  ::apollo::routing::RoutingRequest* mutable_routing_request();
  ::apollo::routing::RoutingRequest* release_routing_request();
  void set_allocated_routing_request(::apollo::routing::RoutingRequest* routing_request);

  // optional .apollo.common.StatusPb status = 6;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 6;
  const ::apollo::common::StatusPb& status() const;
  ::apollo::common::StatusPb* mutable_status();
  ::apollo::common::StatusPb* release_status();
  void set_allocated_status(::apollo::common::StatusPb* status);

  // @@protoc_insertion_point(class_scope:apollo.routing.RoutingResponse)
 private:
  void set_has_header();
  void clear_has_header();
  void set_has_measurement();
  void clear_has_measurement();
  void set_has_routing_request();
  void clear_has_routing_request();
  void set_has_map_version();
  void clear_has_map_version();
  void set_has_status();
  void clear_has_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::RoadSegment > road_;
  ::google::protobuf::internal::ArenaStringPtr map_version_;
  ::apollo::common::Header* header_;
  ::apollo::routing::Measurement* measurement_;
  ::apollo::routing::RoutingRequest* routing_request_;
  ::apollo::common::StatusPb* status_;
  friend struct protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoutingRequest

// optional .apollo.common.Header header = 1;
inline bool RoutingRequest::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RoutingRequest::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RoutingRequest::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RoutingRequest::clear_header() {
  if (header_ != NULL) header_->::apollo::common::Header::Clear();
  clear_has_header();
}
inline const ::apollo::common::Header& RoutingRequest::header() const {
  const ::apollo::common::Header* p = header_;
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.header)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::common::Header*>(
      &::apollo::common::_Header_default_instance_);
}
inline ::apollo::common::Header* RoutingRequest::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::apollo::common::Header;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingRequest.header)
  return header_;
}
inline ::apollo::common::Header* RoutingRequest::release_header() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingRequest.header)
  clear_has_header();
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void RoutingRequest::set_allocated_header(::apollo::common::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingRequest.header)
}

// repeated .apollo.routing.LaneWaypoint waypoint = 2;
inline int RoutingRequest::waypoint_size() const {
  return waypoint_.size();
}
inline void RoutingRequest::clear_waypoint() {
  waypoint_.Clear();
}
inline const ::apollo::routing::LaneWaypoint& RoutingRequest::waypoint(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.waypoint)
  return waypoint_.Get(index);
}
inline ::apollo::routing::LaneWaypoint* RoutingRequest::mutable_waypoint(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingRequest.waypoint)
  return waypoint_.Mutable(index);
}
inline ::apollo::routing::LaneWaypoint* RoutingRequest::add_waypoint() {
  // @@protoc_insertion_point(field_add:apollo.routing.RoutingRequest.waypoint)
  return waypoint_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneWaypoint >*
RoutingRequest::mutable_waypoint() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.RoutingRequest.waypoint)
  return &waypoint_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneWaypoint >&
RoutingRequest::waypoint() const {
  // @@protoc_insertion_point(field_list:apollo.routing.RoutingRequest.waypoint)
  return waypoint_;
}

// repeated .apollo.routing.LaneSegment blacklisted_lane = 3;
inline int RoutingRequest::blacklisted_lane_size() const {
  return blacklisted_lane_.size();
}
inline void RoutingRequest::clear_blacklisted_lane() {
  blacklisted_lane_.Clear();
}
inline const ::apollo::routing::LaneSegment& RoutingRequest::blacklisted_lane(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.blacklisted_lane)
  return blacklisted_lane_.Get(index);
}
inline ::apollo::routing::LaneSegment* RoutingRequest::mutable_blacklisted_lane(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingRequest.blacklisted_lane)
  return blacklisted_lane_.Mutable(index);
}
inline ::apollo::routing::LaneSegment* RoutingRequest::add_blacklisted_lane() {
  // @@protoc_insertion_point(field_add:apollo.routing.RoutingRequest.blacklisted_lane)
  return blacklisted_lane_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >*
RoutingRequest::mutable_blacklisted_lane() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.RoutingRequest.blacklisted_lane)
  return &blacklisted_lane_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >&
RoutingRequest::blacklisted_lane() const {
  // @@protoc_insertion_point(field_list:apollo.routing.RoutingRequest.blacklisted_lane)
  return blacklisted_lane_;
}

// repeated string blacklisted_road = 4;
inline int RoutingRequest::blacklisted_road_size() const {
  return blacklisted_road_.size();
}
inline void RoutingRequest::clear_blacklisted_road() {
  blacklisted_road_.Clear();
}
inline const ::std::string& RoutingRequest::blacklisted_road(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.blacklisted_road)
  return blacklisted_road_.Get(index);
}
inline ::std::string* RoutingRequest::mutable_blacklisted_road(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingRequest.blacklisted_road)
  return blacklisted_road_.Mutable(index);
}
inline void RoutingRequest::set_blacklisted_road(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:apollo.routing.RoutingRequest.blacklisted_road)
  blacklisted_road_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void RoutingRequest::set_blacklisted_road(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:apollo.routing.RoutingRequest.blacklisted_road)
  blacklisted_road_.Mutable(index)->assign(std::move(value));
}
#endif
inline void RoutingRequest::set_blacklisted_road(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  blacklisted_road_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:apollo.routing.RoutingRequest.blacklisted_road)
}
inline void RoutingRequest::set_blacklisted_road(int index, const char* value, size_t size) {
  blacklisted_road_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.RoutingRequest.blacklisted_road)
}
inline ::std::string* RoutingRequest::add_blacklisted_road() {
  // @@protoc_insertion_point(field_add_mutable:apollo.routing.RoutingRequest.blacklisted_road)
  return blacklisted_road_.Add();
}
inline void RoutingRequest::add_blacklisted_road(const ::std::string& value) {
  blacklisted_road_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:apollo.routing.RoutingRequest.blacklisted_road)
}
#if LANG_CXX11
inline void RoutingRequest::add_blacklisted_road(::std::string&& value) {
  blacklisted_road_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:apollo.routing.RoutingRequest.blacklisted_road)
}
#endif
inline void RoutingRequest::add_blacklisted_road(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  blacklisted_road_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:apollo.routing.RoutingRequest.blacklisted_road)
}
inline void RoutingRequest::add_blacklisted_road(const char* value, size_t size) {
  blacklisted_road_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:apollo.routing.RoutingRequest.blacklisted_road)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
RoutingRequest::blacklisted_road() const {
  // @@protoc_insertion_point(field_list:apollo.routing.RoutingRequest.blacklisted_road)
  return blacklisted_road_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
RoutingRequest::mutable_blacklisted_road() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.RoutingRequest.blacklisted_road)
  return &blacklisted_road_;
}

// optional bool broadcast = 5 [default = true];
inline bool RoutingRequest::has_broadcast() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RoutingRequest::set_has_broadcast() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RoutingRequest::clear_has_broadcast() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RoutingRequest::clear_broadcast() {
  broadcast_ = true;
  clear_has_broadcast();
}
inline bool RoutingRequest::broadcast() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.broadcast)
  return broadcast_;
}
inline void RoutingRequest::set_broadcast(bool value) {
  set_has_broadcast();
  broadcast_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.RoutingRequest.broadcast)
}

// optional .apollo.routing.ParkingInfo parking_info = 6 [deprecated = true];
inline bool RoutingRequest::has_parking_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RoutingRequest::set_has_parking_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RoutingRequest::clear_has_parking_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RoutingRequest::clear_parking_info() {
  if (parking_info_ != NULL) parking_info_->::apollo::routing::ParkingInfo::Clear();
  clear_has_parking_info();
}
inline const ::apollo::routing::ParkingInfo& RoutingRequest::parking_info() const {
  const ::apollo::routing::ParkingInfo* p = parking_info_;
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.parking_info)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::routing::ParkingInfo*>(
      &::apollo::routing::_ParkingInfo_default_instance_);
}
inline ::apollo::routing::ParkingInfo* RoutingRequest::mutable_parking_info() {
  set_has_parking_info();
  if (parking_info_ == NULL) {
    parking_info_ = new ::apollo::routing::ParkingInfo;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingRequest.parking_info)
  return parking_info_;
}
inline ::apollo::routing::ParkingInfo* RoutingRequest::release_parking_info() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingRequest.parking_info)
  clear_has_parking_info();
  ::apollo::routing::ParkingInfo* temp = parking_info_;
  parking_info_ = NULL;
  return temp;
}
inline void RoutingRequest::set_allocated_parking_info(::apollo::routing::ParkingInfo* parking_info) {
  delete parking_info_;
  parking_info_ = parking_info;
  if (parking_info) {
    set_has_parking_info();
  } else {
    clear_has_parking_info();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingRequest.parking_info)
}

// optional bool is_start_pose_set = 7 [default = false];
inline bool RoutingRequest::has_is_start_pose_set() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RoutingRequest::set_has_is_start_pose_set() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RoutingRequest::clear_has_is_start_pose_set() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RoutingRequest::clear_is_start_pose_set() {
  is_start_pose_set_ = false;
  clear_has_is_start_pose_set();
}
inline bool RoutingRequest::is_start_pose_set() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.is_start_pose_set)
  return is_start_pose_set_;
}
inline void RoutingRequest::set_is_start_pose_set(bool value) {
  set_has_is_start_pose_set();
  is_start_pose_set_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.RoutingRequest.is_start_pose_set)
}

// -------------------------------------------------------------------

// RoutingResponse

// optional .apollo.common.Header header = 1;
inline bool RoutingResponse::has_header() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RoutingResponse::set_has_header() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RoutingResponse::clear_has_header() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RoutingResponse::clear_header() {
  if (header_ != NULL) header_->::apollo::common::Header::Clear();
  clear_has_header();
}
inline const ::apollo::common::Header& RoutingResponse::header() const {
  const ::apollo::common::Header* p = header_;
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingResponse.header)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::common::Header*>(
      &::apollo::common::_Header_default_instance_);
}
inline ::apollo::common::Header* RoutingResponse::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::apollo::common::Header;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingResponse.header)
  return header_;
}
inline ::apollo::common::Header* RoutingResponse::release_header() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingResponse.header)
  clear_has_header();
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void RoutingResponse::set_allocated_header(::apollo::common::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingResponse.header)
}

// repeated .apollo.routing.RoadSegment road = 2;
inline int RoutingResponse::road_size() const {
  return road_.size();
}
inline void RoutingResponse::clear_road() {
  road_.Clear();
}
inline const ::apollo::routing::RoadSegment& RoutingResponse::road(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingResponse.road)
  return road_.Get(index);
}
inline ::apollo::routing::RoadSegment* RoutingResponse::mutable_road(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingResponse.road)
  return road_.Mutable(index);
}
inline ::apollo::routing::RoadSegment* RoutingResponse::add_road() {
  // @@protoc_insertion_point(field_add:apollo.routing.RoutingResponse.road)
  return road_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::routing::RoadSegment >*
RoutingResponse::mutable_road() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.RoutingResponse.road)
  return &road_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::routing::RoadSegment >&
RoutingResponse::road() const {
  // @@protoc_insertion_point(field_list:apollo.routing.RoutingResponse.road)
  return road_;
}

// optional .apollo.routing.Measurement measurement = 3;
inline bool RoutingResponse::has_measurement() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RoutingResponse::set_has_measurement() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RoutingResponse::clear_has_measurement() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RoutingResponse::clear_measurement() {
  if (measurement_ != NULL) measurement_->::apollo::routing::Measurement::Clear();
  clear_has_measurement();
}
inline const ::apollo::routing::Measurement& RoutingResponse::measurement() const {
  const ::apollo::routing::Measurement* p = measurement_;
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingResponse.measurement)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::routing::Measurement*>(
      &::apollo::routing::_Measurement_default_instance_);
}
inline ::apollo::routing::Measurement* RoutingResponse::mutable_measurement() {
  set_has_measurement();
  if (measurement_ == NULL) {
    measurement_ = new ::apollo::routing::Measurement;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingResponse.measurement)
  return measurement_;
}
inline ::apollo::routing::Measurement* RoutingResponse::release_measurement() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingResponse.measurement)
  clear_has_measurement();
  ::apollo::routing::Measurement* temp = measurement_;
  measurement_ = NULL;
  return temp;
}
inline void RoutingResponse::set_allocated_measurement(::apollo::routing::Measurement* measurement) {
  delete measurement_;
  measurement_ = measurement;
  if (measurement) {
    set_has_measurement();
  } else {
    clear_has_measurement();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingResponse.measurement)
}

// optional .apollo.routing.RoutingRequest routing_request = 4;
inline bool RoutingResponse::has_routing_request() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RoutingResponse::set_has_routing_request() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RoutingResponse::clear_has_routing_request() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RoutingResponse::clear_routing_request() {
  if (routing_request_ != NULL) routing_request_->::apollo::routing::RoutingRequest::Clear();
  clear_has_routing_request();
}
inline const ::apollo::routing::RoutingRequest& RoutingResponse::routing_request() const {
  const ::apollo::routing::RoutingRequest* p = routing_request_;
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingResponse.routing_request)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::routing::RoutingRequest*>(
      &::apollo::routing::_RoutingRequest_default_instance_);
}
inline ::apollo::routing::RoutingRequest* RoutingResponse::mutable_routing_request() {
  set_has_routing_request();
  if (routing_request_ == NULL) {
    routing_request_ = new ::apollo::routing::RoutingRequest;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingResponse.routing_request)
  return routing_request_;
}
inline ::apollo::routing::RoutingRequest* RoutingResponse::release_routing_request() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingResponse.routing_request)
  clear_has_routing_request();
  ::apollo::routing::RoutingRequest* temp = routing_request_;
  routing_request_ = NULL;
  return temp;
}
inline void RoutingResponse::set_allocated_routing_request(::apollo::routing::RoutingRequest* routing_request) {
  delete routing_request_;
  routing_request_ = routing_request;
  if (routing_request) {
    set_has_routing_request();
  } else {
    clear_has_routing_request();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingResponse.routing_request)
}

// optional bytes map_version = 5;
inline bool RoutingResponse::has_map_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RoutingResponse::set_has_map_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RoutingResponse::clear_has_map_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RoutingResponse::clear_map_version() {
  map_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_map_version();
}
inline const ::std::string& RoutingResponse::map_version() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingResponse.map_version)
  return map_version_.GetNoArena();
}
inline void RoutingResponse::set_map_version(const ::std::string& value) {
  set_has_map_version();
  map_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.routing.RoutingResponse.map_version)
}
#if LANG_CXX11
inline void RoutingResponse::set_map_version(::std::string&& value) {
  set_has_map_version();
  map_version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.routing.RoutingResponse.map_version)
}
#endif
inline void RoutingResponse::set_map_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_map_version();
  map_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.routing.RoutingResponse.map_version)
}
inline void RoutingResponse::set_map_version(const void* value, size_t size) {
  set_has_map_version();
  map_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.RoutingResponse.map_version)
}
inline ::std::string* RoutingResponse::mutable_map_version() {
  set_has_map_version();
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingResponse.map_version)
  return map_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoutingResponse::release_map_version() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingResponse.map_version)
  clear_has_map_version();
  return map_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoutingResponse::set_allocated_map_version(::std::string* map_version) {
  if (map_version != NULL) {
    set_has_map_version();
  } else {
    clear_has_map_version();
  }
  map_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), map_version);
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingResponse.map_version)
}

// optional .apollo.common.StatusPb status = 6;
inline bool RoutingResponse::has_status() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RoutingResponse::set_has_status() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RoutingResponse::clear_has_status() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RoutingResponse::clear_status() {
  if (status_ != NULL) status_->::apollo::common::StatusPb::Clear();
  clear_has_status();
}
inline const ::apollo::common::StatusPb& RoutingResponse::status() const {
  const ::apollo::common::StatusPb* p = status_;
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingResponse.status)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::common::StatusPb*>(
      &::apollo::common::_StatusPb_default_instance_);
}
inline ::apollo::common::StatusPb* RoutingResponse::mutable_status() {
  set_has_status();
  if (status_ == NULL) {
    status_ = new ::apollo::common::StatusPb;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingResponse.status)
  return status_;
}
inline ::apollo::common::StatusPb* RoutingResponse::release_status() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingResponse.status)
  clear_has_status();
  ::apollo::common::StatusPb* temp = status_;
  status_ = NULL;
  return temp;
}
inline void RoutingResponse::set_allocated_status(::apollo::common::StatusPb* status) {
  delete status_;
  status_ = status;
  if (status) {
    set_has_status();
  } else {
    clear_has_status();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingResponse.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace routing
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto__INCLUDED
